briansmith/ring

- .travis.yml
- mk/update-travis-yml.py
This was previously not done because `g++-4.9-multilib` was not
a whitelisted package on Travis. As of this PR, it is available:
https://github.com/travis-ci/apt-package-whitelist/pull/1117
> Enable testing on 32-bit GCC 4.9 on Travis CI.

- crypto/ec/gfp_p384.c
Without this change, I'm getting errors like:
crypto/ec/gfp_p384.c:69:20: error: unused function 'elem_sqr_mul_mont' [-Werror,-Wunused-function]
static inline void elem_sqr_mul_mont(Elem r, const Elem a, size_t squarings,
^
1 error generated.
> Really fix Mac build

- BUILDING.md
Currently it points to https://github.com/briansmith/ring/blob/master/strawberryperl.com.
> Fix strawberryperl link in BUILDING.md

- BUILDING.md
- build.rs
- mk/top_of_makefile.mk
- build.rs
* Default to `gmake` on BSD systems
* Support optional `MAKE` variable for pointing to correct `make`
- mk/top_of_makefile.mk
* Allow target triple on *BSD not to have abi (e.g. x86_64-unknown-freebsd)
- BUILDING.md
* Add descriptions about `MAKE` variable.
This is take 2 of PR #290 created by @GrappigPanda, and will address the build issue on *BSD systems:
- [Cross compilation on *BSD #287](https://github.com/briansmith/ring/issues/287)
- [FreeBSD compilation error #311](https://github.com/briansmith/ring/issues/311)
Tested on FreeBSD 10.3-RELEASE (amd64) using `cargo test`.
@briansmith @oherrala Can you please review?
> Fix issue #287, #311 - Support building on *BSD

- README.md
The labels were replaced with projects.
> fix links for oxidation and tls-1.3 projects

- src/aead/chacha20_poly1305_openssh.rs
The sequence number is encoded in the SSH wire format, which is big-endian.
Together with the other PR, everything seems to be working fine now.
> Fix nonce encoding in chacha20-poly1305@openssh.com.

- src/aead/chacha20_poly1305_openssh.rs
[From the protocol docs:](http://cvsweb.openbsd.org/cgi-bin/cvsweb/src/usr.bin/ssh/PROTOCOL.chacha20poly1305?annotate=HEAD)
> 37: The first 256 bits consitute K_2 and the second 256 bits become
> 38: K_1.
Ran into this while moving away from libsodium in my SSH library. Any ideas why they chose this backwards order?
> Fix subkey order in chacha20-poly1305@openssh.com

- src/aead/aead.rs
`open` -> `open_in_place`
`seal` -> `seal_in_place`
> Fix function name typos in doc comments.

- src/aead/aead.rs
- src/aead/aes_gcm.rs
- src/aead/chacha20_poly1305.rs
This attempts to improve the API of `ring::aead` by at least a marginal amount by fixing #371 (Removing the `in_prefix_len` parameter from `open_in_place()`) and #291 (fixing the processing of `out_suffix_capacity` in seal_in_place()`), and by returning slices instead of lengths from these functions.
Feedback is much appreciated. I'd like to improve this API more, but we're constrained because these APIs must (IMO): 1. be in-place, 2. be non-allocating, and 3. enforce that the tag is serialized immediately after the ciphertext.
Note that I plan to offer a not-in-place API in addition to this API, which maybe will use `std::io::Write` or similar, which I suspect will be less error-prone.
/cc @Philipp91 @mcginty @frewsxcv
> Improve the usability of `ring::aead`.

- .travis.yml
- README.md
- build.rs
- mk/update-travis-yml.py
I stopped defining `__ANDROID_API__` which means we drop support for gcc on android. This is a PR for issue #473.
> Use clang on android.

- build.rs
Since https://github.com/alexcrichton/cc-rs/pull/294 this crate has stopped compiling on iOS targets with:
```
clang: error: -fdata-sections is not supported with -fembed-bitcode
clang: error: -ffunction-sections is not supported with -fembed-bitcode
```
> Remove -fdata-sections and -ffunction-sections (let cc set these if needed)

- build.rs
Try to fix the compile error for Visual Studio 2017 (15.7.*)
#648
> ignore new C5045 VS2017 warning

- BUILDING.md
- build.rs
This pull requests removes the code that automatically defines the `__ANDROID_API__` constant, and replaces it by a code that checks whether the constant has been defined by something else.
In other words, we now assume that the user manually defines `__ANDROID_API__`, for example through the `CFLAGS` environment variable.
The main reason is practical. If you generate a standalone NDK toolchain in order to compile your project, the wrapper automatically passes the `__ANDROID_API__` constant to the actual compiler. Therefore if you try to compile *ring* for the standalone toolchain, you will most likely get a compilation error because the constant passed by the standalone conflicts with the one defined by ring.
I don't know how widely used *ring* for Android is, but I'm open to feedback …
> Check __ANDROID_API__ instead of defining it automatically

- .travis.yml
- mk/travis-install-android.sh
- mk/update-travis-yml.py
> Use clang on travis with Android

- tests/pbkdf2_tests.txt
[RFC link](https://tools.ietf.org/html/rfc7914#section-11).
> Add PBKDF2-HMAC-SHA256 test vectors from RFC 7914

- crypto/chacha/asm/chacha-x86.pl
The x86 PerlAsm translator makes every function external except for
ones with names that start with an underscore. Consequently,
`ChaCha20_ssse3` had public visibility, unintentionally. Fix that.
> Stop exporting `ChaCha20_ssse3`.

- appveyor.yml
- mk/appveyor.bat
Use rustup to install rust on AppVeyor.
Unfortunately rustup always [installs rust's documentation](https://github.com/rust-lang-nursery/rustup.rs/issues/998), so this may slow down CI builds on Windows.
I agree to license my contributions to each file under the terms given at the top of each file I changed.
> Use rustup on AppVeyor

- STYLE.md
- crypto/fipsmodule/cipher/e_aes.c
- src/aead/aes_gcm.rs
- src/bssl.rs
- src/ec/curve25519/ops.rs
- src/poly1305.rs
- src/rand.rs
- src/rsa/bigint.rs
Resolves #451.
This PR changes the definition of some foreign functions to return a `bssl::ErrorCode` instead of `c::int`. 
Converting to a `Result` is now done through a conversion function rather than `bssl::map_result`. It also defines marker traits for the two widely used return code conventions in this library:
* 1 for success (used in most BoringSSL functions)
* 0 for success
> Use `#[repr(transparent)]` newtype to hold FFI error codes

- crypto/fipsmodule/aes/aes.c
- crypto/fipsmodule/aes/internal.h
- crypto/fipsmodule/cipher/e_aes.c
- src/aead/aes_gcm.rs
Resolves #113.
`GFp_AES_set_encrypt_key` can fail if and only if the following invariants are violated.
* All pointer arguments must be non-null.
* The key size must be either 128 or 256 bits (192 bit keys [aren't supported](https://github.com/briansmith/ring/commit/b3e91be71edde28f5d2884d3c3c34260b6a79378)).
The first invariant should not be checked at runtime (except via assertion) as it is the responsibility of the caller.
The second could be expressed statically by accepting an enum with the valid key lengths, but enums don't provide any type safety in C. Instead, we document the acceptable key lengths and make them the responsibility of the caller.
As a result of these changes, `GFp_AES_set_encrypt_key` (as well as `GFp_aes_c_set_encrypt_key`) no longer needs to return an error code. …
> Make caller enforce invariants when setting AES encryption key

- crypto/fipsmodule/aes/asm/aesni-x86.pl
- crypto/fipsmodule/aes/asm/aesni-x86_64.pl
- crypto/fipsmodule/modes/asm/aesni-gcm-x86_64.pl
Resolves #705 for code using x86{,_64} AES-NI extensions. 192-bit key support still exists in ARM assembly.
Since *ring* does not support AES with 192-bit keys, we can remove some unused assembly code.
Comments were added to indicate that 192-bit key support was willfully removed, and also to indicate where control-flow changed based on key size.
This extends the work done in commits 1103cf29dfbbf51f0dd8fb757084caa052863869 and b3e91be71edde28f5d2884d3c3c34260b6a79378.
> Remove 192-bit key support from AES-NI assembly.

- src/signature.rs
Disable the generic signing API when `use_heap` isn't enabled.
> Fix `--no-default-features` build.

- crypto/limbs/limbs.c
- src/limb.rs
- src/rsa/bigint.rs
Refactor the code to make it clearer how (timing) side channels are
avoided, and to make it a total function. Move this generic logic from
`rsa` to `limbs`.
>  Refactor `limbs_minimal_bits`.

- Cargo.toml
- src/aead.rs
- src/aead/aes_gcm.rs
- src/aead/block.rs
- src/aead/chacha.rs
- src/aead/chacha20_poly1305.rs
- src/aead/chacha20_poly1305_openssh.rs
- src/aead/poly1305.rs
- src/ec/curve25519/ed25519/signing.rs
- src/ec/curve25519/ed25519/verification.rs
- src/ec/curve25519/x25519.rs
- src/error.rs
- src/polyfill.rs
- src/polyfill/convert.rs
- tests/aead_tests.rs
`TryFrom<&[T]> for &[T; $N]` is in libstd already, but `TryFrom` isn't stable. Add our own `TryFrom_` that's like `TryFrom` to tide us over until it becomes stable.
Similarly, define a new `From_` type that allows us to define conversions from `&[T; $N * 2]` to (&[T; $N], &[T; $N])`, i.e. the array analog of `slice::split_at()`. Currently we only split in half but it's obvious how to extend this to other ratios.
> Replace `slice_as_array_ref!` and `slice_as_array_ref_mut!`

- crypto/cpu-arm-linux.c
- include/GFp/cpu.h
- include/GFp/mem.h
Require `getauxval`. Don't bother worrying about the very old,
now-EoL, devices with broken NEON.
> Remove heap allocation & file I/O from crypto/cpu-arm-linux.c.

- src/aead/quic.rs
I also threw in the key derivation function, since if the rest is going to live here then I think it makes sense for it to as well. I'm not sure if we should additionally get rid of `new`. Test vector taken from Quinn.
We could further simplify `HeaderProtectionKey::derive` by taking a `&'static super::Algorithm`, but it's not clear to me that it's reasonable to expect the set of AEADs implemented by *ring* to remain a subset of the AEADs supported by QUIC.
> Expand QUIC header protection API

- STYLE.md
The "Submodules and file naming" section ended with three backticks (` ``` `), which caused the next section to be formatted as code instead of using proper Markdown formatting.
> Remove misplaced code block boundary in STYLE.md

- src/aead.rs
- src/aead/aes_gcm.rs
- src/aead/chacha20_poly1305.rs
- src/aead/gcm.rs
This allows `Aad` to be returned by value from functions, which is useful in
many cases.
> Allow `Aad` to own its contents.

- .travis.yml
- README.md
- mk/travis-install-android.sh
- mk/travis.sh
Fixes #603 and we can also close #473 even though the switch to clang didn't happen in this pr.
> Build Android targeting API 26 and test with API 24 system image.

- Cargo.toml
- src/cpu.rs
Eliminate one of the two remaining problems with `#![no_std]` support
and reduce platform variance.
> Replace libstd with spin crate in `cpu::cache_detected_features`.

- src/cpu.rs
- src/rand.rs
This is another attempt for ring to support fuchsia, by directly calling `zx_cprng_draw` to generate random byte strings. This avoids having to pull in an extra dependency (which #634 did). With this change, all the ring tests pass on fuchsia.
Closes #428
> Add support for fuchsia's CPRNG source

- crypto/fipsmodule/aes/asm/aesv8-armx.pl
Resolves #705 for ARM targets.
192-bit key support still exists in AES implementation for ARMv8. Remove it, and leave comments documenting where code was removed.
AFAICT, neither the ARMv4 nor the vector-permutation based ARMv7 implementations support 192-bit keys.
This continues the work in 1103cf29dfbbf51f0dd8fb757084caa052863869 b3e91be71edde28f5d2884d3c3c34260b6a79378 and #707.
> Remove 192-bit AES support in ARM assembly.

- tests/digest_tests.rs
[rust-lang/rust#57882](https://github.com/rust-lang/rust/pull/57882) is modifying the `unused_doc_comments` lint to fire on mistakenly documented macro expansions. A crater run detected that this crate will break due to this change, likely because of the use of `deny(unused_doc_comments)` or `deny(warnings)`.
While this kind of breakage is allowed under Rust's stability guarantees, I am opening PRs to affected crates to reduce the impact.
This PR protects your crate from future breakage by converting the offending doc comment to a regular comment.
> convert doc comment to regular comment

- src/rsa/signing.rs
It seems the bitness specified is not the correct one for the example at
hand. Fix it.
> Fix documentation around openssl RSA pkcs8 commands

- src/aead/chacha.rs
- src/digest.rs
- src/digest/sha1.rs
- src/ec/curve25519/ed25519/signing.rs
- src/ec/curve25519/ed25519/verification.rs
- src/ec/suite_b/ecdh.rs
- src/ec/suite_b/ecdsa/signing.rs
- src/ec/suite_b/ecdsa/verification.rs
- src/ec/suite_b/ops.rs
- src/error.rs
- src/io/der_writer.rs
- src/io/writer.rs
- src/lib.rs
- src/pkcs8.rs
- src/polyfill.rs
- src/rand.rs
- src/rsa/bigint.rs
- src/rsa/padding.rs
- src/rsa/signing.rs
- src/signature.rs
- src/test.rs
Right now, `src/lib.rs` defines *ring* to be a `no_std` crate conditionally based on the features and CPU architecture. This is sub-optimal, as it requires a lot of `cfg` attributes to be kept in sync. Both [`rand`](https://crates.io/crates/rand) and [`rdrand`](https://crates.io/crates/rdrand) have dealt with this kind of problem, and they use the following solution.
- The create is unconditionally `#![no_std]`
- If `std` is needed, it can be brought in with `extern crate std`
- There are no bare `use std` or `use core` statements (as they are never necessary)
This is what I did in this PR. Some advantages to this PR:
- It is now very easy to see what ring is depending on from `std`. This helps with:
- https://github.com/briansmith/ring/issues/744
- Eventually making ring's tests work …
> Simplify core vs std usage

- mk/appveyor.bat
Tested download with HTTPS, it is supported now.
This will fix #810 .
> Download binary from tortall.net with HTTPS instead of HTTP

- BUILDING.md
- Cargo.toml
- STYLE.md
- src/aead/chacha.rs
- src/arithmetic.rs
- src/arithmetic/bigint.rs
- src/bits.rs
- src/digest.rs
- src/ec/suite_b/ecdsa/verification.rs
- src/ec/suite_b/ops.rs
- src/error.rs
- src/io.rs
- src/io/der_writer.rs
- src/io/writer.rs
- src/lib.rs
- src/limb.rs
- src/rsa/padding.rs
- src/rsa/signing.rs
- src/rsa/verification.rs
- src/signature.rs
- src/test.rs
- tests/agreement_tests.rs
- tests/ecdsa_tests.rs
- tests/error_tests.rs
- tests/pbkdf2_tests.rs
- tests/rsa_tests.rs
This raises the minimum version of Rust required to 1.36.
> Make `std` an optional dependency. Require `alloc` instead.

- src/digest.rs
- src/hmac.rs
Shrink the size of `hmac::Key` by 256 bytes. Shrink the size of `hmac::Context` by 128 bytes.
In theory it would be possible to eliminate two 'completed_data_blocks: u64' and one `pub algorithm: &'static Algorithm` from each `Key`, and one `completed_data_blocks: u64` and one `pub algorithm: &'static Algorithm` from each `Context` but I don't think those are large enough wins to bother right now.
> Reduce the size of `hmac::Key` and `hmac::Context`

- BUILDING.md
- Cargo.toml
- src/error.rs
- src/lib.rs
- src/rand.rs
- src/test.rs
Dont enable `std`-based functionality unless requested. This requires removing
the `std` feature dependency from `dev_urandom_fallback` and `test_logging`.
Tweak the meaning of `test_logging` to keep this tractable.
> Make `std` a non-default feature.

- src/aead.rs
- src/digest/sha2.rs
These attributes now lead to a compile error on nightly. See [this Rust PR](https://github.com/rust-lang/rust/pull/65294) for more information.
> Remove `#[inline]` attributes on function prototypes

- build.rs
See clippy::into_iter lint and https://github.com/rust-lang/rust/pull/65819
> Use slice::iter

- src/digest/sha2.rs
It is important that the SHA-2 implementation is inlined all the time
because performance on debug builds is way too bad if it isn't, and that
bad performance badly hurts testing.
> Use `#[inline(always)]` consistently in sha2.rs `rotr` functions.

- .travis.yml
- mk/update-travis-yml.py
Thigns are failing with an "Illegal instruction" error. I initially thought
it was specific to Rust 1.40 but it is now happening with Rust 1.39 too, so
I'm assuming something changed in the emulator or NDK, since the Android SDK
isn't locked in CI/CD yet.
> Temporarily disable armv7-linux-androideabi on Travis CI.

- src/digest/sha1.rs
The first commit is just a minor style fix that doesn't really warrant it's own PR.
The second commit speeds up SHA1 computation by ~50-60%. See the commit message for details. Unfortunately it does make the code a bit uglier than I initially expected because Rust doesn't support [destructuring assignments](https://github.com/rust-lang/rfcs/issues/372) (yet?). Still, even for an implementation like ring's, that favors simplicity over speed, the trade-off  is worth it in my opinion.
There's an alternative with much nicer code and the same speedup in [this branch](https://github.com/LingMan/ring/commits/sha1-speedup-crunchy). However, that turned out to increase the binary size by almost 390 KiB. Since ring is targeting small devices, that seamed unacceptable. Therefore I'm PRing this …
> Speed up SHA1 computation

- Cargo.toml
- src/rand.rs
This is a step towards removing the spin-rs dependency. `lazy_static!`'s
conditial use of spin-rs based on a feature flag was particularly problematic
because often other dependencies would enable that feature flag even in cases
where the `std::sync::Once` implementation was preferable.
> Switch `dev_urandom_fallback` to use `once_cell` instead of `lazy_static!`

- Cargo.toml
From
https://doc.rust-lang.org/cargo/reference/manifest.html#the-exclude-and-include-fields
"The options are mutually exclusive: setting include will override an
exclude."
> [cargo] Remove no-op 'exclude' field

- build.rs
Previously, build.rs. would print "cargo:..." to stdout if a variable
`$cargo` was set. This conflicted with Cargo's interpretation of
"cargo:..." to direct it to do things; see [1].
Instead, write to stderr to avoid the conflict. Also change the
formatting of the the environment variable logging so that even if
stderr gets redirected to stdout, such conflicts won't occur.
[1]
https://doc.rust-lang.org/cargo/reference/build-scripts.html#outputs-of-the-build-script
> Fix the case where a `cargo` environment variable is set in build.rs.

- crypto/fipsmodule/modes/internal.h
- src/aead/aes_gcm.rs
- src/aead/gcm.rs
Clarify some pointer aliasing in gcm.rs by removing the questionable `key_aliasing` pattern. It was much easier to remove it than to figure out if it is guaranteed to work. Clarify how keys and contexts are passed to the non-Rust GCM code. Although these changes are justified on their own, they also make merging upstream BoringSSL changes easier. The individual commit messages each contain more detailed explanation.
> Clarify GCM FFI code

- src/aead/aes_gcm.rs
- src/aead/block.rs
- src/aead/chacha20_poly1305.rs
- src/aead/gcm.rs
- src/aead/nonce.rs
- src/aead/poly1305.rs
It seems like we have a couple of instances where we create multiple `&mut` references to the same object. Stop doing that to make it clearer that the Rust rules are being followed. The individual commits have more details.
> AEAD: Reduce the amount of `unsafe` code in `Block`

- src/aead/aes.rs
The code was using the "aliasing pointer" pattern to avoid needing to
deal with `core::mem::uninitialized()`. Now we can use
`core::mem::MaybeUninit` instead of either.
> AES: Replace "aliasing pointer" pattern with `MaybeUninit` pattern.

- mk/travis.sh
Recent Rust Nightly removed `-Zno-landing-pads`.
> Fix code coverage test builds in recent Nightly Rust.

- src/aead/aes.rs
- src/aead/gcm.rs
In gcm.rs, also rename `cpu` to `cpu_features` for consistency with other code.
wasm32-unknown-unknown may require 1.37.0 or later.
> Reset MSRV to 1.36 for common platforms.

- Cargo.toml
Cargo may start requiring the readme to be in the published crate.
> Add doc/link-to-readme.md to the published crate.

- appveyor.yml
- mk/appveyor.bat
Use MSVC 2019. Assume the environment is set up correctly.
> Update MSVC configuration used by AppVeyor.

- src/aead/chacha.rs
> ChaCha: use `slice::copy_within` instead of `core::ptr::copy`.

- src/aead/block.rs
- src/aead/counter.rs
- src/endian.rs
Improve the documentation of the module.
Be more idiomatic with the use of bounds. Simplify users accordingly.
Prepare for the removal of `into_raw_value()`.
> Clarify `endian`.

- src/aead/chacha20_poly1305_openssh.rs
- src/digest.rs
- src/endian.rs
Also remove the unnecessary: `T: From<E>` bound.
> Make small arrays of `endian::Encoding` types a little easier to use.

- src/aead/aes.rs
- src/aead/chacha.rs
- src/aead/quic.rs
Remove use of `Block` from `aead::{aes,chacha}::new_mask` API.
Leave internal use of `Block` in `aead::aes::new_mask`
> Remove `Block` from `aead::{aes,chacha}::new_mask`

- src/aead.rs
- src/aead/aes_gcm.rs
- src/aead/poly1305.rs
> Remove the use of `Block` from `aead::Tag`.

- src/pbkdf2.rs
One of the documentation comments for the predefined PBKDF2 algorithms (HMAC-SHA256) was incomplete so this fixes it to be like the others.
This is a very small change, so feel free to take care of this as part of a bigger fix later.
> Fix a PBKDF2 documentation comment typo

- README.md
- src/ec/suite_b/curve.rs
- src/ec/suite_b/ecdh.rs
- src/hmac.rs
- src/signature.rs
It looks like *ring* is using `main` now.
Signed-off-by: Joe Richey <joerichey@google.com>
> Update doc links to use correct branch

- .travis.yml
- mk/travis.sh
- mk/update-travis-yml.py
Building off of #935, I added musl targets for i686 and x86_64 using clang as the compiler. Addresses #713
> Added musl targets

- mk/update-travis-yml.py
`oss` is equivalent to `target.keys()` so eliminate `oss` in favor
of using `target.keys()`.
Similarly, `compilers` duplicates the list of targets. Fold it into
`targets` to eliminate the duplication.
This is a no-op change; `python mk/update-travis-yml.py` generates
the same `.travis.yml` as it did before.
> CI/CD: Avoid duplicating the OS and compiler lists.

- .github/workflows/ci.yml
- Cargo.toml
- mk/install-build-tools.sh
Bump the wasm-bindgen-test dependency version to be compatible with
the latest wasm-bindgen-cli version.
> CI/CD: Test wasm32-unknown-unknown in GitHub Actions.

- .gitattributes
- crypto/.gitattributes
- crypto/fipsmodule/.gitattributes
- crypto/perlasm/.gitattributes
- include/GFp/.gitattributes
GitHub is reporting some include files as C++ instead of C, and it is reporting
some .pl files as Perl instead of Assembly. Attempt to fix that.
Remove superfluous entries in ./.gitattributes and consolidate some of the
.gitattributes files into ./.gitattributes.
> Clean up and fix .gitattributes files.

- build.rs
Avoid any potential for leaking sensitive environment variables that would be irrelevant to the build.
> build:rs Remove printing of environment variables

- .github/workflows/ci.yml
- mk/cargo.sh
Make it easier to build and test the wasm32-unknown-unknown target locally.
> Build: Move wasm32-unknown-unknown support to cargo.sh.

- crypto/curve25519/curve25519.c
- crypto/curve25519/internal.h
- crypto/fipsmodule/aes/aes_nohw.c
- crypto/internal.h
Define `GFp_memcpy` and `GFp_memset` with fallback implementations. Sync up
some code that diverged from BoringSSL due to the lack of these functions.
> Clean up memcpy/memset patterns.

- src/aead/chacha.rs
- src/endian.rs
When we removed the use of `Block` from ChaCha20, we didn't preserve the alignment. Fix that.
BoringSSL uses this declaration of `ChaCha20_ctr32`:
```
void ChaCha20_ctr32(uint8_t *out, const uint8_t *in, size_t in_len,
const uint32_t key[8], const uint32_t counter[4]);
```
> Fix alignment of ChaCha20 keys.

- Cargo.toml
- src/cpu.rs
Clarify that, on ARM/Aarch64, runtime feature detection is done only for Linux (including Android) and Fuchsia. Reduce some of the duplication between Linux and Fuchsia; probably we should do more later.
> cpu.rs: Clarify conditions under which runtime CPU feature detection is done.

- crypto/chacha/asm/chacha-armv4.pl
- crypto/crypto.c
- crypto/fipsmodule/bn/asm/armv4-mont.pl
- crypto/fipsmodule/sha/asm/sha256-armv4.pl
- crypto/fipsmodule/sha/asm/sha512-armv4.pl
- crypto/fipsmodule/sha/asm/sha512-armv8.pl
- src/cpu.rs
Presently on aarch64-apple-* `GFp_armcap_P` is always zero. That's wrong; the
assembly language code needs it to be set correctly, or else the most optimized
code paths (NEON and/or SHA-2 extensions) will never be chosen.
Refactor the code so that `GFp_armcap_P` is set correctly, and to make it easier to
understand and maintain.
This will enable more optimized implementations on aarch64-apple-* targets, whereas
before the lowest common denominator implementations were being used for any
features that did the feature detection in assembly language code instead of Rust.
Move the definition of `GFp_armcap_P` to Rust so wouldn't have to keep C and Rust
code for it in sync. Remove the fallback definitions of `GFp_armcap_P` that use the
".comm"; they would always be set to zero if they were …
> cpu.rs: Refactor and Fix ARM/Aarch64 CPU features handling.

- .github/workflows/ci.yml
- build.rs
- src/cpu.rs
Change the static CPU feature detection logic to assume all aarch64-apple-* targets
have the same capabilities as far as the features we use are concerned.
Use the "ios64" PerlAsm flavour for aarch64-apple-darwin, like OpenSSL upstream does.
Add (build-only) cross-compilation jobs to GitHub Actions.
> Add support for aarch64-apple-darwin.

- Cargo.toml
According to https://github.com/shepmaster/rust/blob/silicon/silicon/README.md#porting-notes, newever versions of `libc` and `cc` in particular have better support for aarch64-apple-darwin.
> Bump some minimum required dependency versions to better support aarch64-apple-darwin.

- src/error.rs
- tests/ed25519_tests.rs
This reverts commit f06811a150fcded1555911678bbca6dcb5440cda because it changed the
pulic API in a non-backward-compatible way.
> Revert "Remove definitions of deprecated `Error::description()` ..."

- crypto/chacha/asm/chacha-armv4.pl
- crypto/fipsmodule/bn/asm/armv4-mont.pl
- crypto/fipsmodule/sha/asm/sha256-armv4.pl
- crypto/fipsmodule/sha/asm/sha512-armv4.pl
- crypto/fipsmodule/sha/asm/sha512-armv8.pl
commit 8a90093cccf60bd2aaf582fe7e56c0b0eff9b002 regressed the ability to incorporate *ring* into a 32-bit ARM shared library, on 32-bit Android at least.
The symbol needs to be declared `.protected`. Not all assemblers (notably, Apple's) understand `.protected`, so use `.hidden`, which implies `.protected`.
Additionally explicitly declare them as `.extern` even though this isn't required by the assembler.
> Fix linker errors when *ring* is incorporated into a (32-bit Android) ARM shared library.

- Cargo.toml
- src/rand.rs
`once_cell` is a required, not optional, dependency, on these platforms.
> Fix BSD `--no-default-features` build.

- .github/workflows/ci.yml
- README.md
- build.rs
- crypto/internal.h
- include/GFp/check.h
- mk/cargo.sh
- mk/install-build-tools.sh
Allow building for *-*-linux-musl* targets without having the musl C sysroot (headers, etc.) available, and without abusing the glibc sysroot, except temporarily for X86_64.
Add aarch64-linux-musl and armv7-unknown-linux-musleabihf targets to GitHub Actions.
More discussion about remaining work will be in issue #713.  See the individual commit messages and contents for more details.
> Improve support for *-*-linux-musl* targets

- .github/workflows/ci.yml
- mk/cargo.sh
- mk/install-build-tools.sh
- mk/runner
Gather code review data to help guide the code review process. This is currently limited to i686, x86_64, and AArch64 Linux because these are the targets I could get working. More investigation is needed to figure out how to collect coverage data for ARM targets.
> CI/CD: Gather code test coverage.

- crypto/chacha/asm/chacha-armv8.pl
Similar error and fix as https://github.com/briansmith/ring/pull/1109
but for chacha-armv8.
Resolves error:
= note: ld.lld: error: relocation R_AARCH64_ADR_PREL_PG_HI21 cannot be used against symbol GFp_armcap_P
; recompile with -fPIC
chacha-armv8-linux64.o:(GFp_ChaCha20_ctr32) in archive libring-core/android_arm64_armv8-a_static/libring-core.a
> Fix another linker error for arm 32-bit Android

- .github/workflows/ci.yml
https://blog.rust-lang.org/2020/11/27/Rustup-1.23.0.html#support-for-apple-m1-devices
says that the beta channel supports M1 targets now.
> CI/CD: Enable building of aarch64-apple-darwin targets on Rust Beta.

- .github/workflows/ci.yml
`cargo install cargo-deny` takes 7 minutes, while running it takes 2 seconds.
> CI/CD: Cache the cargo-deny binary to speed up the `deny` job.

- .github/workflows/ci.yml
AFAICT, the previous attempt at caching didn't work because, AFAICT,
~/.cargo/{.crates.toml, .crates2.json} were not cached.
> CI/CD: Try again to cache cargo-deny.

- .github/workflows/ci.yml
See https://github.com/actions/virtual-environments/issues/2155. This fixes
CI/CD jobs failing due to `apt-get` failing to download packages.
> CI/CD: Run `sudo apt-get update` before using `apt-get`.

- .github/workflows/ci.yml
- build.rs
- src/aead/aes.rs
- src/arithmetic/bigint.rs
- src/lib.rs
- tests/aead_tests.rs
- tests/agreement_tests.rs
- tests/digest_tests.rs
- tests/ecdsa_tests.rs
- tests/ed25519_tests.rs
- tests/hkdf_tests.rs
- tests/hmac_tests.rs
- tests/pbkdf2_tests.rs
- tests/quic_tests.rs
- tests/rsa_tests.rs
Deal with CI testing breakage caused by a change to the warning behavior of the most recent Rust Nightly.
Do what's needed to become compatible with Rust Stable Clippy.
Check with both the current Rust Stable Clippy and 1.37's (MSRV) Clippy.
See the individual commit messages for more details.
> Clean up more warning-related stuff

- .github/workflows/ci.yml
- src/arithmetic/bigint.rs
It is too tedious to maintain compatibility with the MSRV version of Clippy *and* the latest stable version. Drop the use of the MSRV version.
Instead, do full testing on the MSRV, for release-mode builds only, for targets where 1.37.0 works with our recommended configuration.
> CI/CD: Run tests on MSRV; use only latest stable Clippy

- src/endian.rs
The original version avoided `unsafe` but doesn't work for older
versions of Rust that we're still trying to support. Switch to the
`unsafe` implementation that works everywhere.
> Endian: Allow `ArrayEncoding` to be implemented for larger arrays.

- Cargo.toml
- build.rs
- crypto/cipher_extra/asm/chacha20_poly1305_x86_64.pl
- src/aead/chacha.rs
- src/aead/chacha20_poly1305.rs
- src/cpu.rs
Which is significantly faster.
This new PR keeps the original BoringSSL asm interface.
> Enable the integrated assembly x86-64 ChaCha20-Poly1305 implementation from BoringSSL

- src/error.rs
- tests/ed25519_tests.rs
This was reverted in PR #1108 because it broke backward compatibility.
> Remove definitions of deprecated `Error::description()` and `Error::cause()`.

- src/agreement.rs
- tests/agreement_tests.rs
Many (most?) KDFs are infallible, so optimize for that case. If the KDF
is fallible then the result will be `Ok(Err(_))` which is messy.
This eliminates the `error_value` parameter.
> Agreement: Stop requiring the KDF to return a `Result`.

- src/aead.rs
- src/aead/aes.rs
- src/aead/aes_gcm.rs
- src/aead/block.rs
- src/aead/chacha.rs
- src/aead/chacha20_poly1305.rs
- src/aead/chacha20_poly1305_openssh.rs
- src/aead/gcm.rs
- src/aead/gcm/gcm_nohw.rs
- src/aead/poly1305.rs
Reduce uses of `Block` and `BLOCK_LEN` in the ChaCha20-Poly1305 implementation, and remove one of the ugliest parts of `Block`. From here we should be able to reimplement `Block` in terms of the `endian` module and further clean it up.
> ChaCha20-Poly1305: Remove superfluous uses of `Block` and `BLOCK_LEN`.

- src/digest.rs
- src/endian.rs
We don't need it now that `ArrayEncoding::as_byte_array()` can handle larger
arrays.
> Remove `endian::as_byte_slice()`.

- src/aead/aes.rs
- src/aead/aes_gcm.rs
- src/aead/block.rs
- src/aead/gcm.rs
- src/aead/gcm/gcm_nohw.rs
- src/endian.rs
Remove all the `unsafe` blocks from `Block` by reimplementing it using
`endian`. Simplify the API for endian-swapping.
> Reimplement `Block` in terms of `endian` and simplify its API.

- src/aead/chacha.rs
Change the definition of `BLOCK_LEN` to the more useful/correct one that
can be used by the upcoming Rust implementation of ChaCha.
> ChaCha: Clarify `BLOCK_LEN`.

- src/aead/chacha.rs
- src/aead/chacha20_poly1305.rs
Emulate the `copy_within` API so that the use of `unsafe` can be isolated
into a single place.
Remove the test for encryption into disjoint buffers. We should expose
such an API in the future, but currently we don't, so this was testing a
scenerio that would never occur. Removing this part of the test was
necessary to enable this refactoring. We'll need to bring it back when
we implement out-of-place encryption.
> ChaCha: Reduce the use of `unsafe`; emulate the `copy_within` API.

- .github/workflows/ci.yml
- src/aead/aes.rs
This allows us to use more `const fn` goodness and no more
`array::LengthAtMost32` limitations.
> Bump MSRV to 1.47.0.

- src/aead/opening_key.rs
> AEAD: Fix typo in docs for `OpeningKey::open_within`.

- .github/workflows/ci.yml
macos-11.0 is pre-production. Use macos-latest instead, to (I hope)
make macOS jobs more likely to succeed. (Presently, they frequently
fail with no logs.)
Upgrade to Xcode 12.4 in hopes that this will make things work.
> CI: Always use `macos-latest` and Xcode 12.4.

- mk/install-build-tools.sh
https://github.com/actions/virtual-environments/issues/2252 is the best
description of the difference I have found.
Also stop using `sudo`; maybe this was a holdover from Travis CI days?
> CI: Use Android "cmdline-tools" instead of SDK tools.

- mk/cargo.sh
See if this prevents some of the wasm32 failures.
> CI: Increase wasm-bindgen-test timeout to 60s.

- src/aead.rs
- src/aead/aes_gcm.rs
- src/aead/chacha.rs
- src/aead/chacha20_poly1305.rs
- src/aead/chacha20_poly1305_openssh.rs
- src/aead/gcm.rs
- src/aead/less_safe_key.rs
- src/aead/quic.rs
> AEAD internals: Have each AEAD key type remember the CPU features.

- src/aead/chacha.rs
The compiler complained that `words` is never read in situations where
it is passed to the assembly code as a `Key`, relying on `Key` being
`#[repr(transparent)]`.
We've been moving away from using `repr(transparent)` for these kinds of types. Do
that here to solve this problem and also to continue that general trend. Use
`words_less_safe()` instead of directly accessing `words` to reduce the amount of
conditional logic.
> ChaCha internals: Clarify usage of internal value of `Key`.

- .github/workflows/ci.yml
- mk/clippy.sh
- src/lib.rs
Add mk/clippy.sh to make it easier to run Clippy with the same configuration as is used in CI.
Always run Clippy jobs using a separate target directory to work around the Clippy caching bug.
Disable some new (as of the most recent Rust release) lints that weren't triggered previously.
Clippy sometimes adds and/or removes lints. To prevent the *ring* source from being sensitive to that, move the `allow` directives that disable some Clippy lints from lib.rs to the command line in mk/clippy.sh.
> "Fix" clippy job

- build.rs
Assume by default that an operating system does not have an ABI compatible
with the PerlAsm sources. Add all the operating systems that we've
explicitly added support for to the allowlist. Avoid trying to build or
use the PerlAsm code for those targets.
On top of this, we can build fallback logic for using Rust (or C)
implementations for those targets that aren't compatible with the
assembly.
> Only use assembly code on known-compatible OS+Arch combinations.

- .github/workflows/ci.yml
Follow the advice near the end of
https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/
> Minimize GITHUB_TOKEN permissions and avoid persisting it.

- .github/workflows/ci.yml
This is a step towards implementing the GitHub security hardening advice.
```
$ sed -ri 's|(uses: +)([^/]+)/([^@])|\1briansmith/\2-\3|g' .github/workflows/ci.yml
$ grep "uses:" .github/workflows/ci.yml | sort | uniq
- uses: briansmith/actions-cache@v2
- uses: briansmith/actions-checkout@v2
- uses: briansmith/actions-rs-toolchain@v1
- uses: briansmith/codecov-codecov-action@v1
```
> CI/CD: Use my own fork of (third-party) GitHub Actions.

- build.rs
- src/prefixed.rs
Eliminate one place where the prefix would have to be manually updated.
> Pass prefix from build.rs to src/prefixed.rs through `cargo:rustc-env`.

- Cargo.toml
- build.rs
Now "links" in Cargo.toml is the only thing that needs to be manually modified
when the prefix changes.
build.rs enforces that the package name and version are consistent with the
"links" field.
> Build: Derive FFI symbol prefix and FFI lib prefix from Cargo.toml "links".

- src/rand.rs
Instead of maintaining our own implementation, just defer to libc.
This will enable ports to more architectures.
> Linux: Use `libc::SYS_getrandom` for syscall number.

- src/ec/suite_b/ecdsa/signing.rs
- tests/ecdsa_tests.rs
Resolve an old TODO now that we can make breaking API changes.
> ECDSA: Add RNG as an input parameter to `EcdsaKeyPair::from_pkcs8`.

- src/aead.rs
- src/aead/aes.rs
- src/aead/aes_gcm.rs
- src/aead/chacha.rs
- src/aead/gcm.rs
- src/aead/less_safe_key.rs
- tests/aead_tests.rs
OpeningKey and SealingKey intentionally avoid implementing Copy and
Clone, because they're attached to a fixed nonce sequence that should be
unique. LessSafeKey isn't attached to a nonce sequence, though, and
making it Clone lets callers avoid repeating key setup work.
Coming from https://github.com/briansmith/ring/pull/1158#issuecomment-765050031.
> implement Clone for LessSafeKey

- Cargo.toml
0.17.0-alpha.9 was released off the b/0.17.0-alpha.9 branch. Similarly for
0.17.0-alpha.10 on the b/0.17.0-alpha.10 branch.
Having the version number on the main branch say "0.17.0-alpha.9" or any
version number like that is confusing and misleading. We have to have a
version number, so use one that's clearer while we work on finishing
0.17.0.
> Cargo.toml: Clarify version number.

- src/io/der.rs
No semantic change; using `skip_to_end()` is just clearer.
> Use `input.skip_to_end()` instead of `let _ = input.read_bytes_to_end()`.

- src/rsa.rs
- src/rsa/padding.rs
- src/rsa/signing.rs
- src/rsa/verification.rs
- src/signature.rs
Prepare for making the `rsa` module public.
> RSA internals: Stop re-exporting `rsa::padding` items from `rsa`.

- src/rsa/public/components.rs
- src/rsa/verification.rs
Follow the Rust convention of having minimal constraints on type
definitions.
> Reduce constraints on `RsaPublicKeyComponents`.

- src/io/der.rs
- src/io/positive.rs
Use normal error handling instead of panicking. That is, don't require/assume that the caller
of `io::Positive::new_non_empty_without_leading_zeros()` already validated the input. This
adds redundant error checking when it is used by `io::der`, but will simplify (future)
callers outside of `io::der`.
Rename the function.
> Make `io::Positive` parsing API more robust.

- Cargo.toml
This should allow tests to pass on the crates.io release.
Fixes #1301.
> Add missing test file to Cargo's includes.

- Cargo.toml
- src/rsa/public.rs
- src/rsa/public/key.rs
- src/rsa/signing.rs
- src/rsa/verification.rs
Take a step towards having RSA keys support encryption/decryption
in addition to signing/verification.
No functional changes are intended.
Some documentation was moved around.
> RSA: Move `verification::Key` to `public::Key`.

- src/ec/suite_b.rs
- src/pkcs8.rs
- src/rsa/padding.rs
Prepare for the removal of the `PartialEq`/`Eq` implementations from
`untrusted`. The goal of such removal is to make timing leaks more
obvious, and to make the absense of timing leaks more clear.
> Stop using `PartialEq`/`Eq` implementations for `untrusted::Input`.

- Cargo.toml
- README.md
- benches/aead.rs
This PR brings in the AEAD tests from the `crypto-bench` project to *ring*, and then adds a decryption benchmark to augment them.,
The benchmarks were also ported from the nightly only test framework to criterion so they can run on stable.
Here's a sample output of the benchmark suite and the naming convention used:
```
encrypt_tls12_finished_AES_128_GCM
time:   [251.70 us 262.92 us 272.48 us]
change: [-4.9424% +0.6600% +6.4524%] (p = 0.83 > 0.05)
No change in performance detected.
```
> Add AEAD benchmarks

- src/rand.rs
Make it a `const` instead of referencing the value in the system library to save a relocation.
Fixes #1333.
> `kSecRandomDefault` is `NULL`.

- build.rs
Take a step towards supporting Clang as the compiler for -msvc targets.
> build.rs: Use cc-rs's built-in logic for warnings-as-errors.

- src/rand.rs
This isn't actually a global so I'm surprised this lint bothers with it.
> rand: Get rid of warning about `kSecRandomDefault` case.

- .github/workflows/ci.yml
- BUILDING.md
- Cargo.toml
- build.rs
- crypto/crypto.c
- crypto/fipsmodule/ec/ecp_nistz384.inl
- mk/package.sh
- src/cpu.rs
> Windows ARM64 support

- Cargo.toml
Alexander Ovchinnikov (@Alovchin91) wrote:
> [C]ould you please also upgrade cc to 1.0.69? This version contains fixes to
> find MSVC tools on Windows ARM.
> Require cc-rs 1.0.69 or later to improve aarch64-pc-windows-msvc compatibility.

- .github/workflows/ci.yml
This reverts commit c8ca693ff7e6c619e1f2dd8ea915c335836af3a8 so we'll use the latest
nightly in CI. The rustc bug was fixed.
> Revert "CI: Use nightly-2021-08-13 to work around regression in latest Rust nightly."

- .gitignore
- build.rs
See the commit messages of the individual commits for details on each change.
> build.rs: Clarify `package` logic after aarch64-pc-windows-msvc support was added.

- .github/workflows/ci.yml
This logic is a holdover from when Rust 1.47.0 was the MSRV.
> CI: Stop excluding Rust 1.47.0 builds since they are never attempted.

- src/aead.rs
- src/aead/less_safe_key.rs
- tests/aead_tests.rs
This PR implements a new API for `LessSafeKey`, called `open_in_place_separate`. The intention of it is to mirror the API provided by [seal_in_place_separate_tag](https://docs.rs/ring/0.17.0-alpha.10/ring/aead/struct.LessSafeKey.html#method.seal_in_place_separate_tag), providing flexibility to users who may have their tags separate by default or as part of a higher level construction.
I chose not to implement this on `OpeningKey` since it seems like an API that doesn't match up cleanly with the higher level, misuse resistant properties of it.
> Add open_in_place_separate_tag API to LessSafeKey

- src/arithmetic/bigint.rs
- src/rsa/public/key.rs
- src/rsa/signing.rs
- src/rsa/verification.rs
See the individual comment messages for details.
> Use stronger types for the bounds of `PublicExponent`

- src/arithmetic/bigint.rs
- src/rsa.rs
- src/rsa/public.rs
- src/rsa/public/exponent.rs
- src/rsa/public/key.rs
- src/rsa/signing.rs
- src/rsa/verification.rs
Besides organizing things better, this is a step towards exposing a RSA public key type to users of *ring*.
> Move `bigint::PublicExponent` to `rsa::public::Exponent`.

- src/aead/less_safe_key.rs
The types `OpeningKey` and `SealingKey` are not in scope so we need to
qualify them.
> AEAD: Fix rustdoc warnings.

- src/rsa/public/exponent.rs
- src/rsa/public/key.rs
Move the comments citing the standard to more appropriate places. Do the
steps in order.
> RSA: Clarify validity checking for exponents.

- src/bits.rs
- src/lib.rs
- src/rsa.rs
- src/rsa/public.rs
- src/rsa/public/exponent.rs
- src/rsa/public/key.rs
- src/rsa/public/modulus.rs
- src/rsa/signing.rs
- src/signature.rs
- tests/rsa_tests.rs
Expose a set of public types with minimal functionality for RSA public key operations. We'll add new functionality on top of this.
> RSA: Create a new public key type.

- src/io/der.rs
- src/rsa.rs
- src/rsa/keypair.rs
- src/rsa/keypair/components.rs
- src/rsa/signing.rs
- tests/rsa_tests.rs
This makes it easier to implement JWK and similar standards that use non-ASN.1 big-endian encodings for RSA components.
> RSA: Add the ability to construct an `RsaKeyPair` from components.

- src/limb.rs
- src/polyfill.rs
- src/polyfill/array_flat_map.rs
Refactor `limb::big_endian_from_limbs` to use an approach based on
iterators. We will be then be able to use the new `limb::be_bytes`
to implement `rsa::public::Exponent::be_bytes()` and
`rsa::public::Modulus::be_bytes()` and eventually other similar functions.
We want those functions to return `ExactSizeIterator`s.
This is also part of an ongoing process to eliminate replace all the
big-endian/little-endian encoding logic in *ring* w/ use of core APIs.
> Internal: Replace some manual big-endian encoding w/ standard library use.

- src/rsa/padding.rs
- src/rsa/signing.rs
- src/rsa/verification.rs
The digest is never used after encoding, so move it instead of referencing it.
This is more correct since for signing (and soon encryption) the padded value
is only supposed to be used once.
> RSA internals: Move digest instead of passing a reference when doing padding.

- src/rsa.rs
- src/rsa/public/exponent.rs
We shouldn't promise to external users that the exponent will always
fit in a 64-bit integer as in the future we may need to allow larger
exponents.
> RSA: Remove `From<Exponent> for NonZeroU64` implementation.

- src/arithmetic/bigint.rs
- src/rsa/public/key.rs
- src/rsa/public/modulus.rs
- src/rsa/signing.rs
- src/rsa/verification.rs
The tests of `bigint` were not doing CPU feature detection themselves.
Thus they were depending on some other tests that run before them to do
it, or else they were not making use of all the CPU optimizations
possible, and thus not testing all the interesting code paths.
Also, as we are expanding the functionality of the RSA module, it has
become more difficult to track where CPU feature detection has been done
and where it needs to be done. Move the proof that the CPU feature
detection has been done down into the callers of the `bn_` functions
that need CPU feature detection to have been done.
This will also be helpful if/when we expand the use of the `bigint`
module beyond RSA.
> RSA/bigint: Thread proof of CPU feature detection through bigint.

- src/rsa.rs
- src/rsa/public/key.rs
- src/rsa/signing.rs
- src/rsa/verification.rs
`Exponent::exponentiate` will eventually be used for both signature
verification and encrypting using a public key.
> RSA: Split RSA public key arithmetic from signature verification logic.

- src/rsa/signing.rs
When *ring* first started, BoringSSL and OpenSSL upstream were both
using an implementation of constant-time-ish exponentiation that took
shortcuts that made it clearly not constant-time. Long ago, that code
was replaced here and in BoringSSL (and probably OpenSSL upstream), so
this comment is no longer correct.
> RSA: Remove misleading documentation about side channels protection.

- src/rsa/keypair.rs
- tests/rsa_tests.rs
Refactor the implementation of `rsa::KeyPair::sign()` so that the arithmetic can be reused for RSA encryption. Clarify the implementation design decisions.
Also clarify the API, especially w.r.t. failure conditions.
> RSA: Refactor `rsa::KeyPair::sign()` in preparation for adding RSA encryption

- src/rsa/padding.rs
- src/rsa/padding/pkcs1.rs
- src/rsa/padding/pss.rs
Prepare for adding OAEP by organizing the submodule in a way that separates what's shared from what's not shared.
> RSA internals: Split `rsa::padding` into submodules

- build.rs
- src/ec.rs
- src/ec/curve25519.rs
- src/ec/keys.rs
- src/ec/suite_b.rs
- src/lib.rs
- tests/agreement_tests.rs
- tests/ed25519_tests.rs
Ed25519 was disabled for WebAssembly due to some unrelated issues with
getting the X25519 code working in WebAssembly. Temporarily remove the
`agreement` API when targetting WebAssembly to work around those issues
in a way that lets us enabled Ed25519.
> signature: Enable Ed25519 support for wasm32 targets.

- src/aead.rs
- src/aead/opening_key.rs
- src/aead/sealing_key.rs
- src/aead/unbound_key.rs
The [original link to AEAD Paper](http://www-cse.ucsd.edu/~mihir/papers/oem.html) is dead.
According to https://cseweb.ucsd.edu//~mihir/pubs.html we can find the new link is [here](https://eprint.iacr.org/2000/025.pdf).
> fix dead link for AEAD

- src/cpu/arm.rs
This **might not** help to resolve https://github.com/briansmith/ring/issues/1469.
No idea for me :)
**Edit: please ignore what I explained here before.**
> change the comment type in `features!`'s matcher

- mk/check-symbol-prefixes.sh
- mk/install-build-tools.sh
Don't try to use binutils `nm` or the Android SDK `llvm-nm`, since they don't support LLVM's "opaque pointers".
> Always use `llvm-nm` in mk/check-symbol-prefixes.sh.

- .github/workflows/ci.yml
`macos-latest` switched from macos-11 to macos-12 which broke CI. Use a specific version to prevent this from happening.
> CI: Use macOS 12 and remove now-unneeded Xcode hacks.

- .github/workflows/ci.yml
"The Ubuntu 18.04 Actions runner image is being deprecated and will be removed by 12/1/22" according to the GitHub Changelog blog.
> CI: Use Ubuntu 20.04 in GitHub Actions.

- src/cpu/arm.rs
Generalize the tests to make sense on non-Apple targets and run them on all targets.
> cpu: Expand scope of ARM feature detection tests

- .github/workflows/ci.yml
A recent change in the toolchain, possible cc-rs, caused the build to break since we were running `cargo` two different ways with different environment variables.
> CI: Fix doctest testing.

- .github/workflows/ci.yml
- BUILDING.md
- deny.toml
- mk/cargo.sh
- mk/install-build-tools.sh
`clippy` still fails but I'm thinking to just let it continue to fail on this branch since I don't want to risk accidentally changing the MSRV of 0.16.
> 0.16: Update CI configuration so that CI jobs pass

- .github/workflows/ci.yml
- build.rs
- mk/cargo.sh
- mk/install-build-tools.sh
- src/arithmetic/bigint.rs
- src/arithmetic/bigint/bn_mul_mont_fallback.rs
- src/lib.rs
- src/prefixed.rs
Add an implementation of `bn_mul_mont`. Intentionally break the build on big-endian targets so they don't accidentally build/run with incorrect logic. See the individual commit messages for more details. Add mipsel-unknown-linux-gnu to the GitHub Actions test matrix.
> bigint: Provide a fallback implementation for `bn_mul_mont`.

- mk/install-build-tools.sh
When `$ANDROID_NDK_HOME` is set, `mk/cargo.sh` will use it to locate the NDK tools. Thus, we need to ensure that the hack is applied to `$ANDROID_NDK_HOME` when that is set.
I am not sure why I added this line; perhaps it was unintentially left in when the script was being debugged.
> CI: Fix Android builds in GitHub Actions.

- mk/cargo.sh
- mk/check-symbol-prefixes.sh
- mk/install-build-tools.sh
Rust now uses LLVM 16 and writes object files that LLVM 15's `nm` cannot fully understand.
> CI: Use LLVM 16 tools.

- .github/workflows/ci.yml
The CI jobs for this target are failing with this error:
```
error: component 'rust-std' for target 'mipsel-unknown-linux-gnu' is
unavailable for download for channel 'nightly'
```
Remove the target while we investigate.
> CI: (Temporarily?) remove mipsel-unknown-linux-gnu from build matrix.

- src/arithmetic.rs
- src/arithmetic/bigint.rs
- src/arithmetic/bigint/boxed_limbs.rs
- src/arithmetic/bigint/modulus.rs
- src/arithmetic/bigint/n0.rs
- src/arithmetic/bigint/private_exponent.rs
- src/arithmetic/nonnegative.rs
- src/rsa/keypair.rs
The primary goal of this change is to make progress towards a better `arithmetic` API that abstracts over the storage (`BoxedLimbs`, etc.) to better facilitate doing more arithmetic in Rust instead of C, and to reduce the amount of heap allocation done for RSA operations.
The secondary goal is to unblock the merge of the most recent BoringSSL changes into *ring*. This is an issue only accidentally due to the timing of when I last merged BoringSSL into *ring* vs. when I made these changes.
> NFC: Split internal `bigint` module into submodules

- src/rand.rs
Fixes compilation for the target, random is provided by rust-random/getrandom#359
> Add support for PS Vita (armv7-sony-vita-newlibeabihf)

- tests/digest_tests.rs
The code is always enabled since "wasm32" was spelled wrongly. Apparently the wasm-bindgen compatibility issue is no longer an issue.
> NFC: Remove unneeded `#cfg(...)` in digest_tests.rs

- Cargo.toml
- src/cpu/arm.rs
`winapi` is in maintenance mode and the new blessed way to access Windows APIs are the `windows`
and `windows-sys` crates. I don't think any types of `winapi` were exposed in the public API so
I used `windows-sys` since it has much faster compile times.
> deps: Move from `winapi` to `windows-sys`

- Cargo.toml
- src/aead/gcm.rs
- src/digest.rs
- src/endian.rs
- src/rsa/public_exponent.rs
Hey @briansmith, I'm happy to have this merged if it's in a state you're comfortable with, but I also know you were hesitant about taking another dependency. I'd be happy to make any changes or chat about the overall approach.
I can also remove the `derive` feature from `zerocopy` if you'd prefer; that's the bulk of the compilation time (zerocopy itself without the derive is a fairly small library). I'm not sure if compilation time is your primary concern, but I know it is for some crate authors.
> Document or remove some uses of `unsafe`

- src/signature.rs
The original plan was to add RSA encryption/decryption to the next release but that plan has changed. To make it easier for people to upgrade, and to be consistent with the current state of the other signature algorithm keypair names, bring back the old name.
> Bring back the `RsaKeyPair` name.

- .github/workflows/ci.yml
These are duplicated by `coverage` (temporarily) and the `features` tests. Do this to reduce the latency between submitting a PR and it passing CI. Right now we have so many jobs with the huge matrix and CI takes too long.
> Don't run `test` jobs on Beta or Nightly channels.

- .github/workflows/ci.yml
- include/ring-core/target.h
- mk/cargo.sh
- mk/install-build-tools.sh
As there's been few recent activity on related PRs, this is #1574 rebased on latest `main` with:
* git commit-attribution to involved developers and
* sanetized commit messages to match the naming used by ring
Tested and working on Alpine Linux (riscv64 with musl libc).
> Add support and CI workflow for riscv64

- .github/workflows/ci.yml
- include/ring-core/target.h
- mk/cargo.sh
- mk/install-build-tools.sh
- src/cpu/arm.rs
Revive PR #819 (by q66) in reduced-scope by implementing powerpc64le support in ring. This effort supports only little endian machines using POWER8 and later processors for now. The goal is to enable ring to target modern powerpc64le machines.
Only the bare minimum needed to build ring and pass ring tests is included; there is no new optimized code for algorithms already implemented in C/Rust. This has been tested on a POWER9 Blackbird, and on a POWER8 machine.
> Initial ppc64le Support

- .github/workflows/ci.yml
- Cargo.toml
- src/cpu/arm.rs
Our MSRV supports `if` in const expressions. Implement a workaround for buggy detection on older versions of Rust.
> Use `cfg!(target_feature)` for static ARM/AARCH64 feature detection.

- src/cpu/arm.rs
It is possible that a 32-bit ARM target could have static crypto CPU features.
> CPU: ARM: Remove bogus static assertion about 32-bit ARM.

- .github/workflows/ci.yml
- crypto/fipsmodule/aes/aes_nohw.c
- crypto/internal.h
- include/ring-core/target.h
- mk/cargo.sh
- mk/install-build-tools.sh
- src/lib.rs
This adds basic support for Linux on s390x, using the fallback implementation of all algorithms and no assembler routines.   This addresses https://github.com/briansmith/ring/issues/986 and makes "cargo test" fully pass on s390x.
There were two main changes I had to make to get this working:
- Provide a bn_mul_mont fallback implementation.  Note that while there is a fallback implementation on the Rust side for limbs_mont_mul, some elliptic curve code directly calls bn_mul_mont on the C side, where there is currently no fallback.  However, given that we have a bn_from_montgomery_in_place fallback, it is straightforward to add bn_mul_mont (along the lines of the limbs_mont_mul fallback).
- Support big-endian platforms.   This consists of adding a number of endian access primitives in …
> Add basic support for s390x

- include/ring-core/target.h
- mk/cargo.sh
- mk/install-build-tools.sh
Follow up https://github.com/briansmith/ring/pull/1565
> Add support for LoongArch64

- include/ring-core/target.h
- mk/cargo.sh
- mk/install-build-tools.sh
Not added to CI. We need to find a better solution for supporting PowerPC (and s390x and other less-common archs) in CI.
> Add support for 64-bit big-endian PowerPC.

- crypto/fipsmodule/aes/aes_nohw.c
Address some warnings from Clang/GCC in the SSE2 code that are disabled
by default in BoringSSL but not in *ring*.
> AES: Use SSE2-based implementation as the fallback on x86 and x86-64.

- crypto/fipsmodule/aes/aes_nohw.c
This reverts commit 1a5ad00222405b8e64ee322c61942bdd63cc1e29.
Not all C compilers for i686 support SSE2 by default.
> Revert "AES: Use SSE2-based implementation as the fallback on x86 and x86-64."

- src/ec/curve25519/ed25519/signing.rs
- src/ec/curve25519/ops.rs
Combine some `unsafe` blocks and create a more logical interface.
> ECC: Better encapsulate Curve25519 base point multiplication.

- build.rs
- src/rand.rs
This PR allows using ring lib to target [tier 3 *-apple builds](https://doc.rust-lang.org/nightly/rustc/platform-support/apple-tvos.html):
- Apple tvOS on aarch64
- Apple tvOS Simulator on x86_64
> Add apple tvos support

- include/ring-core/target.h
Both powerpc64 and powerpc define `__powerpc__`. Also remove endianness check for powerpc64* since it's not necessary.
> Fix powerpc64 detection

- build.rs
Apparently it is OK to set `-std=c1x` even when compiling assembly code, so just set it no matter what we're compiling. This simplifies the code and allows future simplification.
It's not clear why certain warnings were separated from the others. Combine them too, for the same reasons.
> build.rs: Set compiler C and CPP (preprocessor) flags in one place.

- build.rs
> Clarify build.rs C compiler and linker configuration.

- .github/workflows/ci.yml
> CI: Remove s390x and powerpc64le from `test` matrix.

- Cargo.toml
- doc/link-to-readme.md
The intended effect was to redirect people reading about *ring* on crates.io to the GitHub-hosted README.md. However, the unintended effect was that docs.rs is broken for the 0.17.0 release.
> Remove doc/link-to-readme.md.

- build.rs
- Fix retrieveing `OUT_DIR` in `build.rs`
- Fix getting `CARGO_MANIFEST_DIR`: Use `env::var_os`
- Modify `run_command_with_args` to take `OsStr` instead of `String` for args
- Call `env::var_os` in `read_env_var`
- Change return type to `PathBuf` instead of `String` for fn `compile`
Signed-off-by: Jiahao XU <Jiahao_XU@outlook.com>
> Fix `build.rs`: Use `env::var_os` to retrieve `Path`

- src/agreement.rs
- src/signature.rs
- tests/agreement_tests.rs
- tests/signature_tests.rs
Implement `AsRef<[u8]>` for `signature::UnparsedPublicKey`, making it
possible to access the bytes of the public key. For consistency, I did
the same for `agreement::UnparsedPublicKey`, although it already has a
`bytes` method. `agreement::PublicKey` already uses the `AsRef<[u8]>`
approach.
Also, add missing `Debug` implementation ~and `algorithm` method~ for
`signature::UnparsedPublicKey`.
> Allow accessing signature::UnparsedPublicKey bytes

- build.rs
See individual commit comments. The intent here is to help people understand what's required to adapt build.rs to an alternative build system by making its use of cc-rs more idiomatic.
> build.rs: Use cc-rs in a more canonical way in most cases.

- src/lib.rs
Documentation isn't hosted on briansmith.org anymore.
> Remove `#![doc(html_root_url)]`.

- .github/workflows/ci.yml
`dev_urandom_fallback` presently does nothing, so don't bother adding it as a matrix dimension.
Because `dev_urandom_fallback` does nothing,
`--no-default-features --features=alloc` is effectively the same as the default feature set, so don't add it as a matrix dimension.
`--all-features` is no longer appropriate after the ARM hardware feature disabling features were added, so replace it with what we really want, `--features=std,slow_tests`.
In the coverage section, `--features=alloc,dev_urandom_fallback,std` is the same as `--features=std` since `alloc and `urandom_fallback` are default features.
> CI: Improve feature testing.

- bench/aead.rs
- src/arithmetic/montgomery.rs
These tests don't require libstd functionality, so don't use libstd.
> Tests: Remove superfluous uses of `libstd` in tests.

- build.rs
Our policy is to set warnings-as-errors only when buildingt from Git, not when building from a packaged release. This flag is another aspect of warnings-as-errors.
> build.rs: Remove `-pedantic-errors` from compiler configuration.

- third_party/fiat/curve25519_64_adx.h
See https://github.com/rust-lang/rust/issues/116573.
> Curve25519: Conservatively force noinline on ADX code paths.

- build.rs
Enable further compiler optimizations.
> build.rs: Remove `-fno-strict-aliasing` from the C compiler configuration.

- build.rs
- crypto/curve25519/curve25519.c
- crypto/mem.c
- include/ring-core/mem.h
- src/constant_time.rs
*ring* defined a function named `OPENSSL_memcmp` that did what `CRYPTO_memcmp` does in BoringSSL, and BoringSSL has a different function called `OPENSSL_memcmp`. *ring* doesn't need `OPENSSL_memcmp` so sync the `CRYPTO_memcmp` stuff with BoringSSL.
This eliminates unnecessary differences from BoringSSL.
> Use `CRYPTO_memcmp` name the same as BoringSSL.

- src/aead/block.rs
- src/endian.rs
Remove one `unsafe` from `ring::endian` by completely removing `FromByteArray`.
> NFC: Safety: Remove `endian::FromByteArray`.

- src/aead/chacha20_poly1305_openssh.rs
This is a step towards removing `ArrayEncoding::as_byte_array()`.
> Remove use of `ring::endian` from `aead::chacha20_poly1305_openssh`.

- src/aead/chacha20_poly1305.rs
- src/endian.rs
- src/polyfill/array_flatten.rs
This is a step towards eliminating `unsafe` usage in `ring::endian` by eliminating one use of `ArrayEncoding::as_byte_array`.
Since this is the only usage of `LittleEndian`, it is removed completely.
This simple `array_flatten` polyfill will be useful for multiple improvements towards eliminating the unsafe code in `endian`.
> Remove `LittleEndian` usage from Poly1305 and delete `LittleEndian`.

- src/aead/aes_gcm.rs
- src/aead/block.rs
- src/aead/gcm.rs
- src/aead/gcm/gcm_nohw.rs
These are all steps towards removing the use of `BigEndian<u64>` within `Block`, and thus removing the use of `ring::endian` from `Block`. The new code doesn't use `ring::endian`.
> AES-GCM: Move `u64` <-> `Block` conversions out of `Block` and into callers

- src/aead/block.rs
- src/endian.rs
In particular, eliminate the use of `ArrayEncoding::as_byte_array` as we work towards removing that function because it uses `unsafe`.
Where `Block` is used in parameters to C/assembly code, I verified that the C/assembly code uses `uint8_t *` as the function type (meaning `uint8_t[16]`) in the BoringSSL headers. Until recently the stuff in GCM was using `uint64_t` or a union containing `uint64_t`, which is why block was previously defined in terms of `BigEndian<u64>`.
> AEAD: Remove all use of `ring::endian` and u64 from `Block`.

- src/aead/chacha/fallback.rs
- src/polyfill/chunks_fixed.rs
It is only used in one place so it isn't justified.
> ChaCha20 Polyfill: Remove `ChunksFixedMut`.

- src/aead/aes.rs
- src/aead/chacha.rs
- src/aead/gcm.rs
- src/aead/gcm/gcm_nohw.rs
- src/polyfill/array_split_map.rs
- src/polyfill/chunks_fixed.rs
Replace a few uses of `ChunksFixed` with a new `ArraySplitMap`. `ArraySplitMap` avoids the need to construct an intermediate array; we would hope the optimizer would handle that, but at least in the past it did not always do so.
The approach here isn't very scalable since the source code of each implementation of `ArraySplitMap`  grows twice as fast as the size of the input array. Maybe we can find a cleverer solution, at least for the larger ones.
> Take some steps toward eliminating the last `unsafe` in `ring::polyfill`

- mk/clippy.sh
For a long while this hasn't been needed. See
https://github.com/rust-lang/rust-clippy/blob/master/CHANGELOG.md#rust-152
> Remove `target-dir` workaround for Clippy cache issues.

- build.rs
- mk/clippy.sh
- src/aead/aes.rs
- src/aead/gcm.rs
- src/rsa/padding/pss.rs
See individual commits. This is a step towards moving Clippy configuration to clippy.toml.
> NFC: Reduce clippy lint overrides.

- Cargo.toml
Older versions may work but we've not been testing those old versions.
> Bump dependency requirements to what's been tested.

- mk/clippy.sh
- src/lib.rs
See the individual commits for details. The goal here is to improve the IDE and edit-test cycle experience.
> Rearrange warning configuration

- build.rs
`/Ox` is widely misunderstood to be the flag to enable maximum optimization with MSVC, partly because it used to be called "Full optimzation" in the Visual Studio GUI (it has been changed and now it's called "Optimizations" or "Enable Most Speed Optimizations" which describes it better). The flag to enable maximum optimizaitions however is actually `/O2` ("Maximize Speed"), which was and still is the default flag for release builds in Visual Studio.
https://learn.microsoft.com/en-us/cpp/build/reference/ox-full-optimization?view=msvc-170
https://stackoverflow.com/questions/5063334/what-is-the-difference-between-the-ox-and-o2-compiler-options
If the intention was indeed to have `/O2` minus the flags `/Ox` is missing I would suggest adding a comment
> Let cc-rs choose the correct optimization flags for MSVC (`/O2` instead of `/Ox`)

- .github/workflows/ci.yml
- mk/cargo.sh
- mk/install-build-tools.sh
> Expand 32-bit ARM test coverage

- .github/workflows/ci.yml
Benchmarks require Rust 1.65 or later currently due to benchmark-only dependencies.
Also, benchmarks add a lot of downloading/build time because they have many more dependencies. So, skipping them in these jobs makes them faster.
> CI: Don't test benchmarks in `test` and `test-features` jobs.

- crypto/curve25519/curve25519.c
- include/ring-core/target.h
- src/ec.rs
- src/ec/curve25519.rs
- src/ec/suite_b.rs
- src/lib.rs
- tests/agreement_tests.rs
Enable `ring::agreement` for wasm32 targets using the small implementation of Curve25519.
Use the small Curve25519 implementation of Curve25519 (and P-256) for all targets except for Aarch64 and x86-64.
Besides being smaller, the small implementations are likely more resistant to compiler-introduced side-channels, which is especially important for the wasm32 virtual machine and other targets that we don't QA as thoroughly as AAarch64 and x86-64.
Bring in the previously-removed definition of `fe_mul_llt` from BoringSSL as of commit
8d71d244c0debac4079beeb02b5802fde59b94bd.
> Use small Curve25519 for wasm32 & other non-{aarch64,x86_64}.

- .github/workflows/ci.yml
- Cargo.toml
- build.rs
- mk/cargo.sh
- mk/install-build-tools.sh
- src/rand.rs
- tests/aead_tests.rs
- tests/constant_time_tests.rs
- tests/digest_tests.rs
- tests/ed25519_tests.rs
- tests/hkdf_tests.rs
- tests/hmac_tests.rs
- tests/pbkdf2_tests.rs
- tests/rand_tests.rs
- tests/rsa_tests.rs
- tests/signature_tests.rs
This is based on PR #1568. See the commit message of the first commit for details. Basically I squashed all the commits together from @JanKaul's PR, removed the changes to `build.rs`, and the GitHub Actions configuration, and rebased onto `main`.
For the CI integration, [ring-toolchain](https://github.com/briansmith/ring-toolchain) was updated to include wasmtime for x86-64 Linux. That is used to install wasmtime in CI.
> Adapt tests to work for wasm32-wasi and add wasm32-wasi to CI.

- src/ec/keys.rs
- src/rand.rs
- tests/digest_tests.rs
> wasm32: Enable more tests and clarify `rand` logic

- src/arithmetic.rs
- src/arithmetic/constant.rs
- src/ec/curve25519/scalar.rs
- src/ec/suite_b/ops.rs
- src/ec/suite_b/ops/elem.rs
- src/ec/suite_b/ops/p256.rs
- src/ec/suite_b/ops/p384.rs
The current macro initializer is not uniform across architectures, and doesn't work when the number of 64bit limbs is not exactly half that of 32bit limbs, (i.e. 521 bit).
This change replaces all limbs! initializers with a new const function with hex string initializers, which is more portable and more ergonomic.
> Replace limbs initializer with const from_hex

- src/ec/suite_b/ops/p256.rs
- src/ec/suite_b/ops/p384.rs
p256.rs and p384.rs were inconsistently doing the same thing. Make them consistent. Also in the case of p256.rs, avoid repeating the value of the constant.
> NFC EC: DRY `PRIVATE_SCALAR_OPS.oneRR_mod_n.limbs`

- src/arithmetic/bigint.rs
See each individual commit message.
> bigint elem_exp_consttime: Remove gathering during table construction.

- src/arithmetic/bigint.rs
- src/rsa/public_key.rs
> RSA signature verification: Save one multiplication.

- mk/generate_curves.py
- src/ec/suite_b/ops/p256.rs
- src/ec/suite_b/ops/p384.rs
Add a tool to generate and/or verify NIST curve boilerplate.
Manually sync the formatting of the existing code with the generator.
> Add simplified elliptic curve code generator.

- src/rand.rs
getrandom crate already supports AIX.
> Enable getrandom for AIX

- crypto/curve25519/curve25519.c
> Curve25519: Add missing static assertion.

- crypto/internal.h
Do it because BoringSSL does it. BoringSSL has some other headers it includes here but we intentionally do not have them and/or we intentionally do not include them here (string.h and assert.h).
> Include arm_arch.h in crypto/internal.h.

- src/aead/aes.rs
- src/aead/chacha.rs
- src/aead/gcm.rs
- src/aead/gcm/gcm_nohw.rs
- src/digest/sha1.rs
- src/digest/sha2.rs
- src/ec/suite_b/ecdsa/signing.rs
- src/ec/suite_b/ops/p256.rs
- src/ec/suite_b/ops/p384.rs
- src/endian.rs
- src/io/der_writer.rs
- src/lib.rs
- src/polyfill/chunks_fixed.rs
See each commit message for details.
> Prevent most inappropriate uses of `as` for conversions

- third_party/fiat/curve25519_64_adx.h
Align with the other use of `OPENSSL_memcpy` in `curve25519_64_adx.h`. `string.h` will no longer be needed.
Closes https://github.com/briansmith/ring/issues/1777
> third_party/fiat: replace `memcpy` with `OPENSSL_memcpy`

- src/arithmetic/bigint.rs
- src/arithmetic/bigint/boxed_limbs.rs
- src/arithmetic/bigint/modulus.rs
The original idea of `Width` was that we'd support operatings that worked on multiple same-width but different-modulus values, and/or we'd support splitting a 2N-limb `BoxedLimb` into two N-limb `&[Limb]`, etc. However, as things are now, `Width` doesn't really serve a useful purpose.
> NFC bigint: Remove `Width`.

- src/arithmetic/bigint.rs
Use the same argument order, naming, etc. as the x86-64 version.
> bigint elem_exp_consttime: Make implementations more consistent.

- src/arithmetic/bigint.rs
- src/arithmetic/bigint/modulus.rs
- src/rsa/keypair.rs
- src/rsa/public_key.rs
- src/rsa/public_modulus.rs
Originally we only had `Modulus`. Then we had a need for a temporary `Modulus` without `oneRR` so we created `PartialModulus`. However, there is really nothing "partial" about them. So, improve the naming by renaming `PartialModulus` to `Modulus` and `Modulus` to `OwnedModulusWithOne`. In the future we may refactor things further to separate the ownership aspect from the "has oneRR" aspect.
Instead of just doing a straightforward rename, take this opportunity to refactor the code so that it uses the new `Modulus` whenever `oneRR()` isn't used. This eliminates the duplication of the APIs of the two modulus types, and the duplication of `elem_mul` and `elem_mul_`.
> bigint: Rename PartialModulus to Modulus, Modulus to OwnedModulusWithOne.

- src/rsa/keypair.rs
- src/rsa/public_key.rs
Commit be27e8e25946b2e975258cfb1ea21f6cc4731d8c made this clone unnecessary.
> RSA: Eliminate a redundant clone.

- src/rsa/keypair.rs
Reduce the size of RsaKeyPair by about 15%.
Importantly, this was the only non-temporary (`'static`) `Elem` other than `One`.
> RSA: Remove `q_mod_n` from `RsaKeyPair`.

- crypto/fipsmodule/ec/gfp_p256.c
- crypto/fipsmodule/ec/gfp_p384.c
- mk/generate_curves.py
Generate some of the C boilerplate, particularly the large constants. The output is written into target/curves/, and can be merged into the actual code in crypto/fipsmodule/ec/ using a two-way merge tool; this is the same as the Rust code generation.
Changes to gfp_p{256,384}.c are due to differences in the generator's output:
* The generator doesn't generate trailing commas in arrays.
* The generator consistently avoids adding leading zeros to hex constants, and consistently format values less than 10 in decimal; the exiting code used a mix of styles.
* The generator wraps arrays consistently; the existing code used a mix of wrapping styles.
* The generator does not nest constants in the functions that need them. This was changed to support future refactorings.
* In order to support …
> Extend elliptic curve code generator to generate C code boilerplate.

- Cargo.toml
- src/lib.rs
- src/rand.rs
This Cargo feature treats a user-provided `getrandom` implementation as a secure random number generator (`SecureRandom`). The feature only has effect on targets not supported by `getrandom`.
closes #1734
> add an opt-in less-safe-getrandom-custom feature

- src/cpu.rs
- src/cpu/arm.rs
This is my attempt at the suggested alternative approach @briansmith suggested in https://github.com/briansmith/ring/pull/1800
> getauxval isn't defined on uclibc, so disable dynamic feature detection

- src/arithmetic/bigint.rs
- src/arithmetic/bigint/modulus.rs
- src/limb.rs
- src/rsa/keypair.rs
See individual commit messages for details. The effect is to make RSA signature verification and RSA signing slightly faster.
> bigint: Calculate 1*R and 1*RR slightly more efficiently.

- bench/aead.rs
The `zip()` was written intending it to work like a Cartesian product, but of course `zip()` doesn't do that. Do an actual Cartesian product.
> bench aead: Do Cartesian product, not zip.

- src/ec/suite_b/ecdsa/digest_scalar.rs
- src/ec/suite_b/ops.rs
- src/limb.rs
It only had one caller and it contained unreached code.
> Refactor away parse_big_endian_in_range_partially_reduced_and_pad_consttime.

- src/ec/suite_b/ecdsa/signing.rs
- src/ec/suite_b/ops.rs
Use the pattern we typically use where one argument is passed by value.
This lets us use `limbs_add_assign_mod`, eliminating the `unsafe` direct use of `LIMBS_add_mod`. This will make future refactoring easier.
This also eliminates the need to construct and zeroize a new scalar `r` for the result.
> ec: NFC: Refactor `scalar_sum` to eliminate `LIMBS_add_mod` use.

- src/arithmetic/bigint/modulus.rs
- src/arithmetic/nonnegative.rs
- src/rsa/keypair.rs
After 5ed0a45c65074a0640e6f9e21512a8c4d9540f1e we no longer needs `p` or `q` in `Nonnegative` form.
> rsa: NFC: Eliminate unnecessary `Nonnegative` -> `Modulus` conversion.

- src/arithmetic/bigint.rs
- src/arithmetic/bigint/modulus.rs
- src/rsa/keypair.rs
- src/rsa/public_key.rs
- src/rsa/public_modulus.rs
`PublicModulus` and `PrivatePrime` are basically duplicates of `OwnedModulusWithOne`. In the future we would like to create an `OwnedModulus` that doesn't need 1RR to be calculated. Also in the future we'd like to be able to "take" 1RR from a public modulus. This change is a step towards those ends.
> bigint: NFC: Take `oneRR` out of `OwnedModulus`.

- src/arithmetic/bigint.rs
- src/arithmetic/bigint/modulus.rs
This was necessary at some point in the past, but no longer is. It is better to avoid depending on any of the `core::fmt` machinery in these lower layers if we can avoid it.
> bigint: Stop implementing `Debug` for `OwnedModulus`.

- src/arithmetic/bigint.rs
- src/arithmetic/montgomery.rs
- src/rsa/keypair.rs
This saves two private-modulus-length multiplications per RSA private key operation at the cost of two private-modulus-length squarings per `RsaKeyPair` construction.
> RSA: Precompute R**3 and store it instead of R**2.

- BUILDING.md
This PR just adds a new clang path to the `BUILDING.md` when the host is a Windows ARM64.
It was tested by building a Rust project using ring 0.17.5 on a Windows 11 ARM64 (M1 Parallels VM) successfully.
Otherwise, I should get an error similar to the following:
```log
ring-0.17.5\build.rs:673:9:
failed to execute ["clang" "-O3" "--target=aarch64-pc-windows-msvc" "-ffunction-sections" "-fdata-sections" "--target=aarch64-pc-windows-msvc" "-I" "include" "-I" "C:\\Users\\joseluisq\\devel\\static-web-server\\target\\aarch64-pc-windows-msvc\\release\\build\\ring-400e2572fe09d335\\out" "-Wall" "-Wextra" "-fvisibility=hidden" "-std=c1x" "-pedantic" "-Wall" "-Wextra" "-Wbad-function-cast" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" …
```
> Docs: Add clang path for Windows ARM64 hosts

- src/arithmetic.rs
- src/arithmetic/bigint.rs
- src/arithmetic/bigint/modulus.rs
- src/arithmetic/nonnegative.rs
- src/rsa/keypair.rs
Check `d` by processing it as a `OwnedModulus` like we do for the other moduli. This should make the checking more consistent.
As a nice side effect, this eliminates the last non-test usage of `Nonnegative` and elimnates more now-dead `Nonnegative` code.
> rsa: Stop using `Nonnegative` in `RsaKeyPair` to check `d`.

- crypto/crypto.c
- src/arithmetic/montgomery.rs
- src/cpu.rs
- src/cpu/arm.rs
- src/prefixed.rs
We want all of our internal symbols to be internal so that none of these internal symbols leak from a static/dynamic library that is built with *ring* inside.
> Stop exporting unmangled symbols on ARM/AArch64.

- Cargo.toml
- src/cpu.rs
- src/cpu/arm.rs
- src/cpu/intel.rs
Commit f932b941bd1f59782cb3db8f7cd7b8b2c9842ee9 was incomplete and wrong. On targets where we do any static or dynamic feature detection and where we have these global variables, we need to unconditionally write the detected features to the global variable so that assembly can see them. Since we do static feature detection regardless of operating system, the initialization of the global most be done without any conditions on the operating system.
> cpu arm: Fix static feature detection initialization.

- .github/workflows/ci.yml
See the individual commit messages for details. This testing catches the issue fixed by PR #1842.
> CI: Update macOS runners to macOS 13 and start running tests for aarch64-apple-darwin.

- src/arithmetic/bigint.rs
- src/arithmetic/montgomery.rs
Have all calls from Rust go through `mul_mont`, which ensures CPU feature detection has been done.
> montgomery: Encapsulate Rust uses of bn_mul_mont.

- src/ec/suite_b/ecdh.rs
- src/ec/suite_b/ecdsa/digest_scalar.rs
- src/ec/suite_b/ecdsa/signing.rs
- src/ec/suite_b/ecdsa/verification.rs
- src/ec/suite_b/ops.rs
- src/ec/suite_b/ops/elem.rs
- src/ec/suite_b/private_key.rs
Provide a better API to (internal) users of `ec::suite_b::ops` so they don't have to do their own low-level slice indexing.
This is also a step towards a better `ops` API that also handles the `cpu::Features` aspects.
> ec suite_b: Encapsulate access to limbs of scalars and field elements.

- src/aead.rs
- src/aead/aes.rs
- src/aead/aes_gcm.rs
- src/aead/chacha.rs
- src/aead/chacha20_poly1305.rs
- src/aead/chacha20_poly1305_openssh.rs
- src/aead/gcm.rs
- src/aead/less_safe_key.rs
- src/aead/poly1305.rs
- src/aead/quic.rs
Have the inner AEAD API take `cpu::features()` for all operations. Then we will be able to write CPU-capability-based tests using (a variation of) the inner API, which will (when implemented) eliminate the need to use SDE and the other various hacks we use for testing all the implementations.
> AEAD: Don't store cpu::Features in the key.

- Cargo.toml
- src/aead/aes.rs
- src/aead/chacha20_poly1305.rs
- src/aead/gcm.rs
- src/cpu.rs
- src/cpu/intel.rs
- src/ec/curve25519/ops.rs
Previously we were relying in part on the compiler and linker to work together to inline always-false guards around calls to architecture-specific functions that might not even exist. However, this isn't guaranteed to work, though so far it always has. Instead, use compile-time logic to guard all architecture-specific calls.
To help ensure tihs happens, only expose `cpu::intel` on Intel targets and similarly only expose `cpu::arm` on ARM targets.
> cpu: Always use #[cfg] for target-arch-specific tests.

- src/aead/chacha20_poly1305.rs
- src/test.rs
This nesting was required in earlier versions of Rust, but not with our MSRV.
> Remove redundant block nesting.

- .github/workflows/ci.yml
https://github.com/briansmith/ring/issues/1679
> CI: add powerpc64-linux to CI

- .github/workflows/ci.yml
Only build/run rustdoc tests once, instead of in every `test` matrix entry.
> CI: Move rustdoc tests to a separate matrix.

- crypto/internal.h
- third_party/fiat/curve25519_64_adx.h
There are some functions that we never want to be (cross-language) inlined, and we expect to add more. Make it easier to add more, and make it easier to extend this capability to more C compilers.
> internal: Add generalized "noinline" attribute support.

- .github/workflows/ci.yml
Running these jobs cost $111.04 in December. Reduce the cost by an expected 75%.
> CI: Use macos-13 instead of macos-13-xlarge for most aarch64-apple-darwin jobs.

- include/ring-core/target.h
New architecture-conditional logic should be done Rust, not in C.
> target.h: Only define `OPENSSL_<arch>` when we have code specific to that arch.

- .github/workflows/ci.yml
- mk/check-symbol-prefixes.sh
See individual commit messages for details. This makes the script portable to all hosts and allows us to expand the symbol prefix checking to all tested targets. It also allows us to avoid incompatibilities between Apple nm and the toolchain's output.
> CI: Use llvm-tools-preview instead of external llvm-tools for symbol prefix testing

- .github/workflows/ci.yml
- include/ring-core/target.h
- mk/cargo.sh
- mk/install-build-tools.sh
Thanks to @DavidHorton5339 for contributing the mips-unknown-linux-gnu changes.
> CI: Add mips-unknown-linux-gnu and mipsel-unknown-linux-gnu to test matrix.

- .github/workflows/ci.yml
- mk/cargo.sh
- mk/install-build-tools.sh
mips64- (big-endian) wasn't added to the test matrix because it isn't enabled in target.h.
> CI: Add mips64el- to test matrix.

- build.rs
In some build systems, target sysroots may use non-standard C extentions like `#include_next`. In such cases, the `-pedantic` flag breaks the compilation.
Resolves issue #1923.
> build.rs: don't use `-pedantic` flag

- src/aead/aes.rs
- src/aead/gcm.rs
Some of the assembly probably assumes NEON is available on Aarch64, so don't remove the assertion in the feature detection logic. But move closer to supporting NEON-less Aarch64 configurations, e.g. within an OS kernel or when NEON is disabled for testing purposes, or when we have a target that for whatever reason doesn't statically enable NEON for AAarch64 and also doesn't support dynamic feature detection.
> aes-gcm: Don't assume NEON is available on AArch64.

- build.rs
This doesn't try to fix every case.
> build.rs: Use named constants instead of string literals more consistently

- .github/workflows/ci.yml
This allows contributors to run the full CI without having to buy GitHub credits. Previously contributors' CI jobs for these targets would fail if they didn't have GitHub Actions credits to spend on macos-13-xlarge runners.
> CI: Use free macos-14 runners for aarch64-apple-* targets.

- Cargo.toml
I was unable to locally test this due to the asm/C code.
I also couldn't run the CI on this commit due to the amount of jobs the CI spawns.
I stripped the non-Windows CIs out on my master branch and the Windows CIs did pass, so I believe this is valid without any actual code edits.
See https://github.com/kayabaNerve/ring/actions/runs/7096652359 for those.
> windows-sys 0.52

- .github/workflows/ci.yml
More recent versions of the toolchain cause the tests to crash with a segmentation fault when built/run with profiling.
> CI: Use nightly-2024-02-13 for code coverage testing.

- Cargo.toml
- build.rs
- src/aead/aes.rs
- src/aead/aes_gcm.rs
- src/aead/gcm.rs
Currently ring bundles an interleaved AES-GCM implementation for aarch64, but does not make use of it, instead calling AES-CTR + GHASH in succession.
This change makes use of the bundled implementation, resulting in speedups of 45% for AES-128-GCM and 55% for AES-256-GCM on Apple M1 CPU.
> aes-gcm: Make use of the optimized aarch64 implementation

- src/aead.rs
- src/aead/aes.rs
- src/aead/aes_gcm.rs
- src/aead/chacha20_poly1305.rs
- src/aead/gcm.rs
- src/aead/less_safe_key.rs
- src/arithmetic/bigint/modulus.rs
- src/bits.rs
- src/limb.rs
- src/polyfill.rs
- src/rsa/keypair.rs
- src/rsa/padding/pss.rs
- src/rsa/public_modulus.rs
- src/rsa/verification.rs
Use `usize`-based math instead of `u64`-based math, addressing the longstanding TODO. Then move the length check into the individual algorithm implementations. Especially in the case of AES-GCM, this makes it clearer that there will be no overflows in the handling of the input lengths. (There weren't any, but this makes that clearer.) See the individual commit messages for details.
> AEAD: Move input length checks to to individual algorithm implementations

- src/aead/aes_gcm.rs
- src/aead/gcm.rs
- src/bits.rs
- src/polyfill.rs
The conversion of bytes to bits looked like it could potentially overflow `usize::MAX`, but it couldn't. Make this more obvious at the call site.
There are two commits. The first one just reorganizes/re-nests code, so it is easier to review this commit-by-commit.
> AES-GCM Aarch64: Clarify bytes -> bits conversion bounds checking.

- build.rs
Remove "-Winline" in particular because it has caused problems for multiple people trying to port *ring* to new targets.
Remove '-Wextra", trusting the C compiler writers' judgement about what should be in "-Wall."
Remove some others since they're more-or-less no longer relevant as we decrease the C code in *ring*.
> build.rs: Remove some previously-added C compiler warnings.

- .github/workflows/ci.yml
- mk/cargo.sh
- mk/install-build-tools.sh
Rust updated to LLVM 18. Use Clang 18 as the C compiler so that the coverage info for C is compatible with that for Rust.
> CI: Use LLVM/Clang 18.

- src/ec/suite_b/ecdsa/signing.rs
- src/io/der.rs
- src/io/der_writer.rs
- src/pkcs8.rs
- src/rsa/padding/pkcs1.rs
- tests/aead_tests.rs
- tests/pbkdf2_tests.rs
See the individual commit messages for details. This is a non-functional change.
> Reduce the number of `as` conversions for integer casts.

- build.rs
Perl is not needed when we are using pregenerated sources, and pregenerated sources are not used when Perl is used to generate them. Clarify this by using an enum that makes the mutual exclusion clear.
> build.rs: Clarify when Perl and pregenerated sources are used.

- .gitignore
- build.rs
Pregenerate .asm files to pregenerated/ instead of pregenerated/tmp.
This simplifies the future prepackaging the symbol prefixing headers for cargo-vendor users.
This also makes progress towards allowing users of `cargo vendor` to eventually assemble the assembly sources on Windows themselves if they prefer.
> Include Windows .asm source files in packaged releases.

- build.rs
Currently it hard-codes an assumption that the build script is run from the $CARGO_MANIFEST_DIR. While this is true for cargo, and typically is true for other build systems, some toolchains may have other requirements.
1e1021d05bdd41cb02bbc43615c9dd7ecd35f853 started encoding that this assumption may not always hold, this commit just extends that other places the assumption is currently made.
This was tested by adding a call to
`std::env::set_current_dir("/tmp").unwrap()` at the top of the build script's `main` function, and has been used to build both the pregenerated version and the non-pregenerated version of the build script.
> build.rs can be run from arbitrary directories

- src/io.rs
- src/io/der_writer.rs
- src/io/writer.rs
- src/rsa/public_key.rs
RsaKeyPair rejects keys that are so large that they can't be serialized by the DER writer, so no panic will happen. However, this is far from obvious, so just make the DER writer fallible instead of having it panic.
> RSA internals: Make it clearer that serializing the public key won't panic.

- src/prefixed.rs
Since `extended_key_value_attributes` was stablized prior to 1.61, we can simplify this macro.
> NFC: Simplify prefixed_item! macro.

- Cargo.toml
- build.rs
- src/prefixed.rs
Instead of having build.rs set a custom environment variable, just compute the value directly from environment variables that are guaranteed to be set. This way, non-Cargo build systems can avoid duplicating this custom logic.
Move the consistency check of `links` and the package version so that the check is also done during pregeneration.
Use `read_env_var()` for the relevant environment variables so that build.rs emits `cargo:rerun-if-env-changed`, as it was noticed that Cargo otherwise doesn't seem to rerun the build script when the Cargo.toml values are changed.
> Use only predefined environment variables to compute name prefixes.

- .github/workflows/ci.yml
- mk/cargo.sh
- mk/check-symbol-prefixes.sh
- mk/install-build-tools.sh
Take a step towards supporting code coverage measurement on non-Ubuntu, non-Linux hosts.
Now clang and llvm-ar is the only thing we need to manually update when Rust upgrades to a new version of LLVM.
> CI: Use llvm-tools-preview for code coverage measurement.

- .github/workflows/ci.yml
- mk/install-build-tools.sh
De-duplicate the logic in ci.yml regarding rustup.
> CI: Use mk/install-build-tools.sh on all targets in CI, and use it for rustup

- src/cpu.rs
- src/cpu/arm.rs
- src/cpu/intel.rs
Make it clearer when reading `arm.rs` and `intel.rs` tthat these modules are only compiled for the relevant target architectures. Remove redundant conditional logic that was confusing regarding this.
> cpu: Clarify `cfg(...)` logic by removing redundant checks.

- src/c.rs
- src/digest.rs
- src/digest/dynstate.rs
- src/digest/sha1.rs
- src/digest/sha2.rs
- src/polyfill.rs
- src/polyfill/slice.rs
Refactor `ring::digest` to minimize the use of `unsafe`.
> digest internals: Refactor to clarify safety

- src/digest.rs
- src/hmac.rs
The assertion in `BlockContext::update` causes the compiler to generate division instructions. Refactor the API to optimize how the data is gathered into full blocks. Also switch from `assert` to `debug_assert`.
> digest internals: Optimize `Context::update`.

- src/digest.rs
- src/digest/sha1.rs
- src/digest/sha2.rs
Previously, the compiler would bounds-check the array slicing in `Digest::as_ref()`. It would also do (and still does, to a lesser extent) unnecessary bounds checks in `BlockContext::{update, finish}` and `Context::{update, finish}`. By using enums instead, the compiler is better able to understand the range (at least) of valid lengths, so it can optimize better. In particular, the compiler can elide some runtime bounds checks with these changes.
> digest internals: Help the compiler understand minimum/maximum output/block sizes.

- src/bits.rs
`x.checked_shl(x)` does NOT check the result against overflow; it only checks that the shift count isn't larger than the bitlength. Use `x.checked_mul(8)` instead of `x.checked_shl(3)` to get the correct effect.
This doesn't seem to have any impact as the inputs are already constrained by additional checks by the users of `BitLength`.
> RSA/AEAD: Check for overflow during byte->bit length conversions.

- src/aead/gcm.rs
`cargo clippy` was complaining when targeting aarch64.
> gcm: add missing #[allow(clippy::assertions_on_constants)] for aarch64

- src/aead/aes.rs
- src/aead/aes_gcm.rs
- src/aead/quic.rs
Merge `bytes` and `variant` into a single parameter that statically guarantees consistency. Use `BitLength` for bit-length parameters in extern functions. Add SAFETY comments.
> AES internals: Clarify safety of `aes::Key::new()`.

- src/aead/aes_gcm.rs
- src/aead/gcm.rs
- src/polyfill/slice.rs
Create polyfills for recently-added slice methods and use them to clarify the safety of `gcm::Context::update_blocks()`. Encapsulate the declarations in a macro and add SAFETY to document the interface.
> AES-GCM: Clarify GHASH assembly safety.

- src/aead/aes_gcm.rs
- src/bits.rs
Make it easier to compare *ring*'s declarations with BoringSSL's for these functions by using u64 instead of usize for the `in_bits` argument to aes_gcm_{dec,enc}_kernel. Use `NonZeroU64` to indicate that the assembly functions do not work with zero-length inputs.
> AES-GCM: Align the types in AArch64 AES-GCM assembly with BoringSSL.

- .github/workflows/ci.yml
v4 requires us to provide the token.
> CI: Upgrade to Codecov v4 action.

- .github/workflows/ci.yml
- Cargo.toml
- build.rs
cc-rs 1.0.x increased its MSRV to 1.63.0, so do likewise, as the extra effort (mainly in ci.yml) to keep supporting 1.61.0 by using an older version of cc-rs isn't justified.
> Update MSRV to 1.63.0.

- src/aead.rs
- src/aead/aes.rs
- src/aead/aes_gcm.rs
- src/aead/algorithm.rs
- src/aead/chacha20_poly1305.rs
- src/aead/less_safe_key.rs
- src/aead/unbound_key.rs
Remove all uses of `KeyInner` and `Algorithm` from the AES-GCM and ChaCha20-Poly1305 implementation submodules, so that both modules become fully statically typed. Encapsulate access to the "methods" of `Algorithm` by moving `Algorithm` and the "implementations" of `Algorithm` to a new submodule that does all the dynamic dispatching.
> aead internals: Eliminate dependency on `KeyInner` from implementations.

- build.rs
- src/aead/aes.rs
- src/aead/gcm.rs
It used to be somewhat common to run 32-bit ARM apps on Aarch64 CPUs, especially for Android, but nowadays that is not the case. Thus the hardware implementations are pretty much dead code. Having them enabled also complicated the testing situation.
> AES-GCM ARM: Don't use hardware AES/GCM on 32-bit ARM.

- src/cpu/arm.rs
unstable-testing-arm-no-hw is intended to disable all feature detection except for NEON. Have the code do exactly that. This way, SHA512 is also handled appropriately, where it wasn't before.
> cpu arm/aarch64: Make unstable-testing-arm-no-hw filter SHA512 too.

- src/bits.rs
The compiler generates pessimistic code when `ok_or` is used.
> bits: Optimize `FromByteLen::from_byte_len` bits constructor.

- src/aead/gcm.rs
Do all the error checking before calling any extern functions in `gcm::Context::new`. This lets the compiler optimize the callers of `gcm::Context::new` better.
> aes-gcm: Do all error checking early in `gcm::Context::new`.

- src/cpu/arm.rs
- src/cpu/arm/linux.rs
Split the 32-bit ARM feature deteection from AArch64 feature detection.
Simpliy the 32-bit ARM feature detection to only look for NEON, so that hardware implementations are never used on 32-bit ARM. In particular, this drops the usage of hardware SHA implementations on 32-bit ARM.
> CPU Linux: Stop detecting non-NEON features on 32-bit ARM.

- .github/workflows/ci.yml
- mk/cargo.sh
Profiler builtins were added in https://github.com/rust-lang/rust/pull/119404.
> CI: Add code coverage mesurement for powerpc-unknown-linux-gnu.

- .github/workflows/ci.yml
Add coverage testing for armv7-unknown-linux-gnueabihf. Move the "no neon" configuration from aarch64- to armv7- since we don't support aarch64-*-linux-* without NEON.
> CI: Add coverage measurement for armv7-unknown-linux-gnueabihf.

- .github/workflows/ci.yml
We were able to add armv7-unknown-linux-gnueabihf without https://github.com/rust-lang/rust/issues/79555 being fixed.
> CI: Remove stale TODO comment.

- src/cpu/arm/darwin.rs
- src/polyfill.rs
- src/polyfill/cstr.rs
- src/polyfill/unwrap_const.rs
Make the memory safety clearer, and make it the check happen at compile time instead of runtime.
> aarch64-apple-*: Use a CStr polyfill in feature detection.

- crypto/fipsmodule/ec/.gitattributes
`.gitattributes` wasn't updated when the file was renamed.
> Fix filename in crypto/fipsmodule/ec/.gitattributes.

- include/ring-core/target.h
- mk/cargo.sh
- mk/install-build-tools.sh
Adds the minimum information to build on sparc64 / sparcv9. Tests pass 100%.
Finally a sore in my conscience gone. Much thanks to the devs from Gentoo and Debian who work very hard to keep these machines in the shape they're in.
For end users: remember to `CFLAGS="-mcpu=ultrasparc" CXXFLAGS="-mcpu=ultrasparc" RUSTFLAGS="-C target-cpu=ultrasparc"`. If you want to build for a higher target, the C/CXX target can be found in `man gcc`, where for rust you can find it with `rustc --print target-cpus`.
Closes: #1512
> Introduce SPARC64 support

- include/ring-core/target.h
Add support for arch csky.
Ref: https://github.com/rust-lang/rust/blob/master/src/doc/rustc/src/platform-support/csky-unknown-linux-gnuabiv2.md
> Add support for arch csky

- src/arithmetic/montgomery.rs
Not only does it not work in this usage, but it actually generated an additional warning about it not working, thus doubling the number of warnings instead.
> bigint: Remove useless `#[allow(deprecated)]`.

- mk/cargo.sh
> CI: Don't pass `-march` to GCC for s390x.

- src/aead/aes.rs
The compiler was generating horrible code.
> aes: Avoid using slice patterns in Counter construction.

- src/aead/aes.rs
- src/aead/aes_gcm.rs
- src/aead/gcm.rs
- src/constant_time.rs
The compiler doesn't transform the byte-wise XORs into word-wise or SIMD XOR. Instead it generated a massive mess of instructions that did it byte-wise. WIth this implementation, it will generate word-wise XOR, at least.
> Specialize constant_time::xor to 16 bytes.

- mk/generate_curves.py
- src/agreement.rs
- src/ec.rs
- src/ec/curve25519/ed25519/signing.rs
- src/ec/curve25519/ed25519/verification.rs
- src/ec/curve25519/ops.rs
- src/ec/curve25519/x25519.rs
- src/ec/keys.rs
- src/ec/suite_b.rs
- src/ec/suite_b/curve.rs
- src/ec/suite_b/ecdh.rs
- src/ec/suite_b/ecdsa/signing.rs
- src/ec/suite_b/ecdsa/verification.rs
- src/ec/suite_b/ops.rs
- src/ec/suite_b/ops/p256.rs
- src/ec/suite_b/ops/p384.rs
- src/ec/suite_b/private_key.rs
- src/ec/suite_b/public_key.rs
Prepare for refactoring how CPU feature detection is done in low-level ECC operations.
In particular, avoid storing CPU features in ec::Seed.
> EC: Thread CPU features through higher-level operations.

- src/cpu.rs
- src/polyfill.rs
- src/polyfill/notsend.rs
- src/test.rs
We don't intend to put `cpu::Features` in any type that could be sent across threads. Enforce this in the type system. This way, we can potentially change the representation of `cpu::Features` to one that really couldn't be `Send` in the future.
> cpu: Make `cpu::Features` be `!Send`.

- src/aead/aes.rs
- src/aead/aes/ffi.rs
Make it clearer which types are used in the FFI and start separating the (unsafe) code for dealing with the C/assembly implementations from the (mostly safe) rest of the code.
`git difftool HEAD^1:src/aead/aes.rs src/aead/aes/ffi.rs`.
> aes: Split FFI helpers into their own submodule.

- src/aead/gcm.rs
- src/aead/gcm/ffi.rs
- src/aead/gcm/gcm_nohw.rs
Make it clearer which types are used in the FFI and start separating the (unsafe) code that's used only for the FFI from the (safe) code used in the Rust implementation.
`git difftool HEAD^1:src/aead/gcm.rs src/aead/gcm/ffi.rs`
> gcm: Split FFI helpers into a separate submodule.

- src/aead/aes.rs
- src/aead/aes/bs.rs
- src/aead/aes/fallback.rs
- src/aead/aes/ffi.rs
- src/aead/aes/hw.rs
- src/aead/aes/vp.rs
- src/aead/aes_gcm.rs
- src/aead/algorithm.rs
- src/aead/gcm.rs
- src/aead/gcm/clmul.rs
- src/aead/gcm/clmulavxmovbe.rs
- src/aead/gcm/fallback.rs
- src/aead/gcm/ffi.rs
- src/aead/gcm/neon.rs
- src/cpu.rs
- src/cpu/arm.rs
- src/cpu/intel.rs
- src/lib.rs
Although every key has been represented with the same types `aes::AES_KEY` and `gcm::HTable` regardless of which implementation is used, in reality those types are polymorphic in ways that aren't captured by the type system currently. Thus, the
`set_encrypt_key!` function must be matched with the corresponding `encrypt_block!` and/or `ctr32_encrypt_blocks!` function. Previously, we did CPU feature detection for each function call and assumed that CPU feature detection is idempotent. Now, we do CPU feature detection during key construction and make the lesser assumption that at least those same CPU features are available as long as the key exists.
This is a step towards making further improvements in CPU-feature-based dispatching.
One side-effect of this change is that GCM keys (and thus …
> aes-gcm: Clarify CPU feature detection.

- src/aead/aes_gcm.rs
The `#[inline(always)]` on `open_strided` was just a mistake.
But, even correcting that, the compiler won't structure `open()` and `seal()` in the expected way. With these changes, the integrated implementations will get inlined (as far as possible) and the compiler will be biased towards assuming they will be used.
> aes_gcm: Prefer integrated implementations, avoid inlining fallbacks.

- include/ring-core/target.h
> Add XTENSA architecture to target.h

- .github/workflows/ci.yml
- STYLE.md
- mk/cargo.sh
- mk/install-build-tools.sh
- src/aead/chacha/fallback.rs
- src/arithmetic/constant.rs
- src/bssl.rs
- src/cpu.rs
- src/cpu/arm.rs
- src/cpu/intel.rs
- src/digest/dynstate.rs
- src/polyfill/array_flat_map.rs
- src/polyfill/cstr.rs
- src/polyfill/notsend.rs
- src/polyfill/slice.rs
- src/rsa/keypair.rs
> CI: Address clippy lints and upgrade tools so CI succeeds

- src/rand.rs
The `getrandom::getrandom` on Fuchsia uses `zx_cprng_draw` to get cryptographically secure random data, which can be seen [here](https://github.com/rust-random/getrandom/blob/master/src/fuchsia.rs).
> Derive SecureRandom for SystemRandom on Fuchsia

- src/ec/suite_b/ops/p256.rs
Back in 2021 a GitHub user "Nik-U" showed a better addition chain for P-256 scalar inversion. This addition chain is slightly better than that one.
> ec: Use 3 fewer squarings for P-256 scalar inversion.

- src/arithmetic/bigint.rs
- src/arithmetic/bigint/modulus.rs
- src/arithmetic/bigint/modulusvalue.rs
- src/rsa/keypair.rs
- src/rsa/public_modulus.rs
We never multiply modulo `d` so avoid constructing `n0` for it. Although `n0` is almost free to construct now, that might change in the future. Also it is better to minimize the amount of processing on the secret value.
```
git difftool HEAD^1:src/arithmetic/bigint/modulus.rs src/arithmetic/bigint/modulusvalue.rs
```
> bigint/rsa: Avoid constructing Montgomery constant for `d`.

- src/limb.rs
> bigint tests: Use `Limb::MAX` instead of `LimbMask::True`.

- src/aead.rs
- src/aead/aes.rs
- src/aead/aes/bs.rs
- src/aead/aes/fallback.rs
- src/aead/aes/ffi.rs
- src/aead/aes/hw.rs
- src/aead/aes/vp.rs
- src/aead/aes_gcm.rs
- src/aead/inout.rs
- src/aead/shift.rs
Notably, `InOut::input_output_len` constructs the `input` pointer from the `output` pointer in a way that safely avoids any concerns about the order of borrowing the (now implicit) input slice and output slice, and in particular whether any such borrowing invalidates any pointers derived from those slices.
Practically, this helps people who are using Miri in its default stacked borrows mode (as opposed to the tree borrows mode) verify the memory safety of our code.
> aead: Support stacked borrows model using a new `InOut` type.

- src/arithmetic/bigint.rs
- src/arithmetic/bigint/boxed_limbs.rs
- src/arithmetic/bigint/modulusvalue.rs
- src/arithmetic/bigint/private_exponent.rs
- src/ec/suite_b.rs
- src/ec/suite_b/ops.rs
- src/limb.rs
Add `LimbMask::leak()` and change all callers to use it. This proactively prevents accidental leakage of the `LimbMask` value and makes it easier to audit the code for places where we intentionally leak the value of a `LimbMask`.
Within the tests, use a `#[cfg(test)]-only wrapper `leak_in_test` to make it easier to see that those leaks are uninteresting.
> arithmetic: Remove `PartialEq` & `Debug` for  `LimbMask`.

- src/constant_time.rs
- src/constant_time/boolmask.rs
- src/limb.rs
`LimbMask` now is an alias for `BoolMask`.
`BoolMask` is now fully opaque to the compiler, instead of being an enum.
> constant_time: Refactor `LimbMask` to `constant_time::BoolMask`.

- mk/generate_curves.py
- src/arithmetic/constant.rs
- src/ec/curve25519/scalar.rs
- src/ec/suite_b.rs
- src/ec/suite_b/ecdsa/verification.rs
- src/ec/suite_b/ops.rs
- src/ec/suite_b/ops/elem.rs
- src/ec/suite_b/ops/p256.rs
- src/ec/suite_b/ops/p384.rs
- src/limb.rs
Take a step toward making `Word` (and `Limb`) opaque types.
This adds some unnecessary copies but the overhead is negligible as those copies are outside of loops.
> ec: Use `LeakyLimb` for public values.

- src/ec/curve25519/scalar.rs
Replace the circuitous range validation with simpler code.
> ec/curve25519: Range check scalars directly.

- src/limb.rs
Take a step towards making `Limb` an opaque type.
Because of inference issues, places where we'd like to write `Limb::from(<literal>)` can't be written that way until `Limb`
(actually `Word`) becomes a newtype. There are only a few of these, so defer them until the actual newtype change happens.
> limbs/bigint: Make obvious LeakyLimb->Limb conversions explicit.

- src/limb.rs
- src/polyfill/slice.rs
Convert from bytes to limbs using `Limb::from_be_bytes`, in a generally more efficient manner, and in a way that avoids doing any arithmetic on the bytes. This addresses the TODO comment about making the constant-timedness of the code clearer.
> limb::parse_big_endian_and_pad_consttime: Rewrite.

- mk/generate_curves.py
- src/ec/suite_b/ops.rs
- src/ec/suite_b/ops/elem.rs
- src/ec/suite_b/ops/p256.rs
- src/ec/suite_b/ops/p384.rs
Help the compiler see that COMMON_OPS.num_limbs, which is used in all the slicing, is always less than the size of the array, so no bounds checks need to be emitted.
> ec/suite_b: Optimize away slice bounds checks.

- mk/generate_curves.py
- src/ec/suite_b.rs
- src/ec/suite_b/ecdh.rs
- src/ec/suite_b/ecdsa/digest_scalar.rs
- src/ec/suite_b/ecdsa/signing.rs
- src/ec/suite_b/ecdsa/verification.rs
- src/ec/suite_b/ops.rs
- src/ec/suite_b/ops/elem.rs
- src/ec/suite_b/ops/p256.rs
- src/ec/suite_b/ops/p384.rs
- src/ec/suite_b/private_key.rs
- src/ec/suite_b/public_key.rs
Rename `Modulus` to `PublicModulus` and add a new `Modulus`:
PublicModulus::limbs: [LeakyLimb; _]
Modulus::limbs: [Limb; _]
Refactor the callers to (approximately) minimize the number of types a `Modulus` is constructed, as it will require a copy if/when `Limb` becomes a type distinct from `LeakyLimb`.
> ec/suite_b: Make more LeakyLimb->Limb conversions explicit.

- src/ec/suite_b/ecdh.rs
- src/ec/suite_b/ecdsa/digest_scalar.rs
- src/ec/suite_b/ecdsa/signing.rs
- src/ec/suite_b/ecdsa/verification.rs
- src/ec/suite_b/ops.rs
- src/ec/suite_b/private_key.rs
- src/ec/suite_b/public_key.rs
`Modulus<M>` is always passed by reference, so when it is constructed, just reference it immediately. This avoids a lot of noise, replacing `&q` with `q` and `&n` with `n`. This reduces the noise of future refactorings where `q` and/or `n` are constructed in a different place.
> ec/suite_b: Consistently use `let {q,n} = &` for moduli.

- mk/generate_curves.py
- src/ec.rs
- src/ec/curve25519/x25519.rs
- src/ec/keys.rs
- src/ec/suite_b.rs
- src/ec/suite_b/curve.rs
- src/ec/suite_b/ecdh.rs
- src/ec/suite_b/ecdsa/digest_scalar.rs
- src/ec/suite_b/ecdsa/signing.rs
- src/ec/suite_b/ecdsa/verification.rs
- src/ec/suite_b/ops.rs
- src/ec/suite_b/ops/p256.rs
- src/ec/suite_b/ops/p384.rs
- src/ec/suite_b/private_key.rs
- src/ec/suite_b/public_key.rs
Follow the same pattern that is used in arithmetic/bigint.rs: Since we have to construct a `Modulus` at roughly the same place we have to get the proof we've done CPU feature detection, just have `Modulus` contain the `cpu::Features`, so that any function that takes a `Modulus` no longer needs a `cpu::Features` argument.
Then, make a step towards threading `cpu::Features` all the way down to to the callers of the lowest-level C/assembly functions. This will facilitate a future refactoring where all dispatching based on CPU features is moved out of the assembly code, from upstream.
> ec/suite_b: Thread CPU features through functions using `Modulus`.

- src/ec/suite_b/ecdsa/signing.rs
- src/ec/suite_b/ops.rs
Callers outside of `ops` use `Modulus` members instead of using `CommonOps` directly.
> ec/suite_b: Minimize scope of `CommonOps` members.

- src/ec/suite_b/ops.rs
- src/ec/suite_b/ops/p256.rs
- src/ec/suite_b/ops/p384.rs
Internally, all the operations do use a single point addition function (per curve) but that's an implementation detail of each operation.
> ec/suite_b: Move `point_sum()` from `CommonOps` to `PrivateKeyOps`.

- build.rs
- crypto/limbs/limbs.c
- src/arithmetic/bigint/modulusvalue.rs
- src/limb.rs
As we require the modulus to be multiple limbs long, its value cannot be less than 3.
> bigint: Remove redundant ">= 3" check for Modulus.

- src/digest.rs
- src/hmac.rs
See the individual commit messages for details. This is a step towards providing a never-panicking variant of the API.
> digest: Clarify panic safety of `(Block)Digest::finish`

- src/digest.rs
- src/digest/dynstate.rs
Avoid calling `format_output` through pointers. It turns out it's more efficient to just do things the straightforward way, as we don't save anything (code size, in particular) with the function pointer approach, as we would with the `block_data_order`. This further clarifies the static analysis of the panic-freeness of `BlockContext::try_finish` as we remove these two unreachable `unreachable!()` calls.
> digest internals: Refactor `format_output`.

- src/digest.rs
- src/hmac.rs
Use `Digest::try_finish()` instead of `Digest::finish()`.
Calculate `num_pending` directly from the inner digest, so that the compiler can use `OutputLen` range analysis to prove that the buffer is large enough.
> hmac internals: Make it clearer that `Context::try_sign` doesn't panic.

- src/aead/aes/ffi.rs
- src/aead/inout.rs
We convert an `InOut` to pointers only immediately prior to calling a function that will immediately invalidate the input. Therefore, it makes more sense for the conversion to consume the `InOut`.
> aes_gcm: Change `InOut` semantics.

- src/aead/aes.rs
- src/aead/aes/ffi.rs
At one point we required `f` to be able to handle empty inputs, but a later refactoring changed that, and added the necessary check before calling `f`, but we forgot to update the comment.
To further clarify things, use `NonZeroU32` when incrementing the counter, since a zero increment would result in a reused counter.
> aes: Clarify empty buffer handling in AES-CTR.

- src/digest.rs
- src/hmac.rs
Make the nature of panics in the HMAC module clearer--`ring::hmac` APIs only panic when the input is too long.
> hmac: Use non-panicking `Digest` API throughout.

- src/aead/aes_gcm.rs
Extend the work done in cb6d5de79c043dfd0004ff1f58aad70631fbd586 to replace pointer arithmetic via slicing with `InOut`'s pointer conversion for integrated AES-GCM opening operations.
Note that sealing doesn't have any arithmetic as it doesn't support a `src` offset.
> aes-gcm: Clarify slice-to-pointer conversion.

- src/error/into_unspecified.rs
- src/error/key_rejected.rs
- src/error/mod.rs
- src/error/unspecified.rs
```
git diff HEAD^1:src/error.rs src/error/key_rejected.rs
git diff HEAD^1:src/error.rs src/error/into_unspecified.rs
git diff HEAD^1:src/error.rs src/error/mod.rs
git diff HEAD^1:src/error.rs src/error/unspecified.rs
```
> error: Split into multiple modules.

- src/aead/gcm.rs
- src/bits.rs
- src/digest.rs
- src/error/input_too_long.rs
- src/error/into_unspecified.rs
- src/error/mod.rs
- src/rsa/public_modulus.rs
- src/rsa/verification.rs
- src/tests/bits_tests.rs
Handle "input too long" errors consistently across the `digest` and `bits` modules. This is a step towards more modules doing the same.
> error handling: Refactor how "Input too long" errors are handled.

- src/aead.rs
- src/aead/aes.rs
- src/aead/aes/bs.rs
- src/aead/aes/fallback.rs
- src/aead/aes/ffi.rs
- src/aead/aes/hw.rs
- src/aead/aes/vp.rs
- src/aead/aes_gcm.rs
- src/aead/overlapping/base.rs
- src/aead/overlapping/mod.rs
- src/aead/shift.rs
> aead internals: Move/rename `aead::inout` to `aead::overlapping`.

- src/aead/aes_gcm.rs
> aes-gcm internals: Clarify `in_out` processing.

- src/digest.rs
- src/hmac.rs
Computing an HMAC can only fail if the input is too long. The other `FinishError` condition, where we failed to meet the precondition for `BlockContext::try_finish()`, is obviously, using information local to the function, unreachable.
Similarly, when there is only a single slice of bytes as input, then the `InputTooLongError` should be the `usize` type, not `u64`. The case where the u64 -> usize condition fails is not interesting, so we use a saturating conversion instead of giving ourselves the future work of proving that it is unreachable.
Finally, remove the `From<FinishError> for error::Unspecified` implementation, in favor of `error::erase`, following the new convention.
> digest/hmac: Clarify error handling.

- src/aead/aes/vp.rs
- src/aead/aes_gcm.rs
- src/aead/algorithm.rs
- src/aead/chacha.rs
- src/aead/chacha/fallback.rs
- src/aead/overlapping/array.rs
- src/aead/overlapping/base.rs
- src/aead/overlapping/mod.rs
Eliminate all of the `unsafe` in the fallback implementation.
> chacha: Use `Overlapping` in the implementation of the fallback impl.

- src/aead/overlapping/array.rs
- src/aead/overlapping/base.rs
- src/digest.rs
- src/polyfill.rs
- src/polyfill/cold_error.rs
See commit messages for details.
> polyfill: Add helper for defining error types.

- src/limb.rs
Since commit e88750b87 ("Define native word size as `constant_time::Word`.") `usize_from_u32()` is unconditionally used in and via global `const`s but was (likely accidentally by means of `rust-analyzer`) merged into a `use` statement that's guarded by `feature = "alloc"`.  When compiling this crate without that feature, which happens with `default-features = false`, this fails to compile due to missing the import.
Moving the import to the unguarded `use crate::` group solves this.
> limb: Unmerge `usize_from_u32` import from `"alloc"`-guarded `use`

- Cargo.toml
- build.rs
- src/aead/aes.rs
- src/aead/aes/bs.rs
- src/aead/aes/ffi.rs
- src/aead/aes/hw.rs
- src/aead/aes/vp.rs
- src/aead/aes_gcm.rs
- src/aead/chacha.rs
- src/aead/chacha20_poly1305.rs
- src/aead/gcm.rs
- src/aead/gcm/clmul.rs
- src/aead/gcm/ffi.rs
- src/aead/gcm/neon.rs
- src/aead/overlapping/base.rs
- src/aead/poly1305.rs
- src/arithmetic/montgomery.rs
- src/bits.rs
- src/cpu.rs
- src/cpu/arm.rs
- src/cpu/arm/linux.rs
- src/digest/sha2.rs
- src/ec/curve25519/x25519.rs
- src/ec/suite_b/ops/p256.rs
- src/lib.rs
- src/polyfill.rs
- src/polyfill/cstr.rs
- src/prefixed.rs
We have this in cpu/arm.rs to force the build to fail for big-endian ARM/AArch64 targets:
```
const _ASSUMED_ENDIANNESS: () = assert!(cfg!(target_endian = "little"));
```
As a step towards removing that restriction, change the `cfg` logic for ARM and Aarch64 to take the endianness into consideration.
Also, don't try to assembly any assembly language sources if the target isn't little endian.
> Restrict usage of assembly code to little endian for ARM & AAarch64.

- src/aead/chacha20_poly1305_openssh.rs
> chacha20_poly1305_openssh: Minimize and document panicking.

- src/aead/chacha20_poly1305_openssh.rs
`open_in_place` takes ciphertext in and outputs plaintext, and it already has a local variable with a name to that effect. It is very confusing to then have a variable named `plaintext_in_ciphertext_out` in this function. Probably it was copy-pasta from `seal_in_place`.
> chacha20_poly1305_openssh: Rename confusing variable (NFC).

- src/aead/chacha20_poly1305.rs
- src/aead/chacha20_poly1305_openssh.rs
Create a new function `begin` that is used by all the opening and sealing operations in both `chacha20_poly1305` and `chacha20_poly1305_openssh`. Inline `derive_poly1305_key` into it.
> chacha20_poly1305 internals: DRY per-packet initialization.

- src/aead/chacha.rs
- src/aead/chacha20_poly1305.rs
- src/aead/chacha20_poly1305_openssh.rs
- src/polyfill/slice.rs
Replace the `pub(super)` IV/Counter API with a simpler, private one.
This makes it clearer that the callers are handling nonces correctly. This will also make it easier to refactor the Counter handling later.
> chacha: Reduce API surface for Counter/IV management.

- src/aead/aes.rs
- src/aead/aes_gcm.rs
- src/aead/chacha.rs
- src/aead/chacha20_poly1305/mod.rs
- src/aead/chacha20_poly1305_openssh.rs
- src/aead/overlapping/base.rs
> chacha: Change name/signature of `encrypt_{in_place,within}`.

- .github/workflows/ci.yml
See individual commits for details.
> CI: Add more CPUs to QEMU-based testing of x86 and run "slow" tests in CPU-model coverage jobs.

- src/arithmetic/bigint.rs
- src/arithmetic/inout.rs
- src/arithmetic/montgomery.rs
> arithmetic: Pass inputs to `limbs_mul_mont` as slices.

- build.rs
- src/rand.rs
with this change, the Nintendo 3DS (`target_os = "horizon"`) can do https (so long as the relevant modifications to the rust standard library are also made to allow TCP to work again)
> Add support for armv6k-nintendo-3ds

- src/arithmetic.rs
- src/arithmetic/bigint.rs
- src/arithmetic/ffi.rs
- src/arithmetic/inout.rs
- src/arithmetic/montgomery.rs
Replace `debug_asesrt!`-based checking with proper error checking. The error cases will never be reached because the callers already ensured that the slices are the correct lengths, but this is more clearly correct.
The previous step defining the `InOut` type didn't work out so well, so replace `InOut` with `AliasingSlices` that does the same thing. The cost is more monomorphization, but that will become moot soon, and it already isn't too bad since there are only three cases to consider. It does help reduce the number of length checks that end up getting generated.
> arithmetic internals: Clarify memory safety of calls to `bn_mul_mont`.

- src/arithmetic/ffi.rs
- src/arithmetic/montgomery.rs
Soon `bn_sqr8x_mont` will stop looking at `OPENSSL_ia32cap_P`, but as of this commit it still does. We already held a `cpu::Features` in the caller so it's a non-issue.
> arithmetic: Clarify `bn_sqr8x_mont` still needs `cpu::Features`.

- src/aead/poly1305.rs
- src/aead/poly1305/ffi_arm_neon.rs
- src/aead/poly1305/ffi_fallback.rs
This will allow the NEON and fallback implementations to evolve separately.
```
diff src/aead/poly1305/ffi_arm_neon.rs \
src/aead/poly1305/ffi_fallback.rs
```
> poly1305: Replace `dispatch!` macro with manual dispatching.

- crypto/poly1305/poly1305.c
- src/aead/chacha20_poly1305/mod.rs
- src/aead/poly1305.rs
- src/aead/poly1305/ffi_arm_neon.rs
- src/aead/poly1305/ffi_fallback.rs
Only pass whole blocks to update, except for the last batch.
> poly1305 internals: Remove the I-U-F logic in poly1305.c.

- src/aead/chacha/ffi.rs
> Make it clearer that we're not passing empty slices to C code.

- src/limb.rs
> limbs internals: Move FFI function declarations into their callers.

- src/arithmetic/bigint/modulusvalue.rs
- src/arithmetic/bigint/private_exponent.rs
- src/limb.rs
It would be questionable to ask if two empty slices of limbs are even, so `limbs_are_even_constant_time` should return an error in that case. Luckily, we already considered empty limbs even (see the test) and callers always return an error on empty limbs. So, nothing changes, except it is clearer that we handle empty inputs correctly.
This is part of a project to clarify what happens when/if/how we pass empty slices to C.
> arithmetic internals: Clarify evenness check for empty limbs.

- src/arithmetic/bigint/boxed_limbs.rs
- src/arithmetic/bigint/modulusvalue.rs
- src/ec/curve25519/scalar.rs
- src/ec/suite_b/ops.rs
- src/limb.rs
Reject empty or non-matching-length inputs. Refactor the internal API so that it is clearer that we're nearly always using this function to reject too-large inputs. This makes it easier to see that it is OK to return an error when previously we didn't.
This isn't intended to have any effect other than making the code easier to audit.
> arithmetic/limbs internals: Clarify limbs < limbs checks.

- src/arithmetic/bigint.rs
- src/ec/suite_b/ecdsa/verification.rs
- src/ec/suite_b/ops.rs
- src/limb.rs
The C variant is still used by the P-384 C code, so leave it.
In ec, combine the `Elem` equality functions into a single implementation that abstracts over the encoding.
This eliminates another call from Rust to a pointer-taking function written in C.
> arithmetic/limbs: Rewrite limbs_equal_limbs_consttime in Rust.

- src/limb.rs
- src/polyfill/slice.rs
Eliminate some uneeded `unsafe` code.
> internals: Replace use of `as_rchunks` polyfill.

- src/aead/aes_gcm.rs
- src/aead/gcm.rs
- src/aead/gcm/clmul.rs
- src/aead/gcm/clmulavxmovbe.rs
- src/aead/gcm/fallback.rs
- src/aead/gcm/ffi.rs
- src/aead/gcm/neon.rs
- src/aead/poly1305.rs
- src/digest/dynstate.rs
- src/digest/sha1.rs
- src/digest/sha2/fallback.rs
- src/digest/sha2/ffi.rs
- src/digest/sha2/sha2_32.rs
- src/digest/sha2/sha2_64.rs
- src/ec/curve25519/scalar.rs
- src/polyfill/slice.rs
- src/polyfill/slice/as_chunks.rs
- src/polyfill/slice/as_chunks_mut.rs
Define new types `AsChunks<T,N>` & `AsChunksMut<T,N>` that act like `&[[T; N]]` and `&mut [[T; N]]`, respectively. Although there is a ton of boilerplate to do this, the advantage is we eliminate the `unsafe` in the implementations of `as_chunks` and `as_chunks_mut`, respectively.
It turns out we only have `flatten`/`flatten_mut` to undo the effects of `as_chunks`/`as_chunks_mut`. The new polyfills have a very natural implementation of flattening: just return the inner slice. Thus, we eliminate the prior use of `unsafe` in flattening easily.
`core` renamed `flatten` and `flatten_mut` to `as_flattened` and `as_flattened_mut`, respectively. Use the new naming.
Move `as_chunks` and related machinery into its own file, and do the same for `as_chunks_mut`. Then we can more easily compare the …
> polyfill: Rewrite `as_chunks`/`as_chunks_mut`/`flatten`/`flatten_mut`.

- src/arithmetic/ffi.rs
- src/arithmetic/inout.rs
- src/arithmetic/montgomery.rs
See each individual commit for details.
> arithmetic: Clarify memory safety aspects of `AliasingSlices` & rename to `AliasingSlices3`

- src/arithmetic/bigint.rs
- src/arithmetic/bigint/modulus.rs
- src/arithmetic/inout.rs
- src/limb.rs
Create an `AliasingSlices2` analog to `AliasingSlices3` to handle unary-ish operations, and use it to clarify the memory safety of a few ops.
> arithmetic: Clarify memory safety of some unary-ish operations.

- src/arithmetic/montgomery.rs
- src/arithmetic/x86_64_mont.rs
It wasn't checking that `r` has the same length as `n`. Make it do that.
> arithmetic: Add missing length check to `bn_sqr8x_mont`.

- src/arithmetic/bigint.rs
- src/arithmetic/x86_64_mont.rs
- src/cpu/intel.rs
- src/limb.rs
- src/rsa/keypair.rs
`elem_exp_consttime` was written weirdly in that it had a bunch of wrappers functions around assembly functions, `bn_gather5`, etc., where the wrapper functions were not marked `unsafe` but also they didn't themselves enforce safety properties. It kind of made sense but technically they should have been `unsafe`. And, there were just a lot of confusing details in how they were written.
Start over with the wrapper functions, and put the new versions of them in the `x86_64_mont` submodule.
We intentionally avoid adding any masking to `power` arguments, which would make them completely safe.
To review this properly, one needs to compare how these functions are documented and used in `crypto/fipsmodule/bn/internal.h` and `crypto/fipsmodule/bn/exponentiation.c` (note this file was renamed in …
> arithmetic: Clarify memory safety of `elem_exp_consttime`.

- src/arithmetic/x86_64_mont.rs
In general we try to avoid function pointers, so avoid them here.
> arithmetic: Call functions directly, instead of through pointer.

- src/arithmetic.rs
- src/arithmetic/bigint.rs
- src/arithmetic/limbs512/mod.rs
- src/arithmetic/limbs512/storage.rs
- src/polyfill/slice/as_chunks_mut.rs
Avoid allocating on the heap. Let the compiler do the alignment instead of manually aligning the start of the table.
> arithmetic: Avoid heap & simplify alignment logic in `elem_exp_consttime`.

- .github/workflows/ci.yml
Remove the explicit selection of the Xcode version.
> CI: Use macos-15 for visionOS builds.

- src/arithmetic/bigint.rs
- src/rsa/keypair.rs
Instead of converting the base from base/R to base*R in place and then copying it into the storage, just write base*R directly into the storage.
> RSA: save two copies during private key operations.

- src/arithmetic/bigint.rs
- src/arithmetic/bigint/modulus.rs
- src/rsa/keypair.rs
Make allocating and zeroing memory for `Elem`s more explicit, towards the goal of eventually removing allocations from low-level functions.
Whenever a function returns an `Elem` by value, have it accept a `Storage` that will be recycled into the return value. Effectively, this moves the allocation from the callee to the caller.
> bigint: Move some memory allocations out of low-level functions.

- src/arithmetic/bigint.rs
- src/arithmetic/bigint/boxed_limbs.rs
- src/rsa/keypair.rs
- src/rsa/public_key.rs
- src/rsa/public_modulus.rs
Make it clearer where cloning an `Elem` causes an allocation to be done, and move those allocations as high up as possible. Replace unnecessary clones.
> bigint: Move allocations for `Elem` cloning from `clone()` to caller.

- src/arithmetic/bigint/boxed_limbs.rs
- src/arithmetic/bigint/modulusvalue.rs
- src/arithmetic/bigint/private_exponent.rs
Take a step towards removing all parsing from `BoxedLimbs`.
This has the added benefit of rejecting more invalid modulus values, notably too-large ones, before allocating memory for them.
> bigint: Move some parsing from `BoxedLimbs` to `OwnedModulusValue`.

- .github/workflows/ci.yml
- src/cpu/intel.rs
- src/digest/sha2/sha2_64.rs
See BoringSSL fcef13a49852397a0d39c00be8d7bc2ba1ab6fb9.
> digest: Enable AVX SHA-{384,512/256,512} on Zen+ AMD CPUs.

- build.rs
- crypto/crypto.c
- crypto/fipsmodule/bn/internal.h
- crypto/internal.h
- src/cpu/arm.rs
Remove `OPENSSL_armcap_P` from Aarch64.
Replace `OPENSSL_armcap_P` with a boolean `neon_available` flag on ARM.
> arm: Minimize the Rust<->C feature detection interface.

- crypto/chacha/asm/chacha-x86_64.pl
- src/aead/chacha.rs
- src/cpu/intel.rs
This makes CPU feature detection simpler and helps the code coverage testing effort.
> chacha: Remove optimized code path for Silvermont-like CPUs.

- src/cpu.rs
- src/cpu/arm.rs
- src/cpu/arm/darwin.rs
- src/cpu/arm/fuchsia.rs
- src/cpu/arm/linux.rs
- src/cpu/arm/windows.rs
- src/cpu/intel.rs
After d39ac0fd8ab26dfe910088841ddc5243df0d9b40 we no longer have the need to be ABI-compatible with the `OPENSSL_armcap_P`-based feature detection.
Remove the tests for that ABI compatibility.
Don't add static CPU feature detection for Intel yet.
Use the same feature flag mechanism as Intel by moving the implementation from intel.rs to cpu.rs and expanding it with the static feature detection capability from arm.rs.
> cpu/arm: Remove old CPU feature detection API; unify with Intel.

- src/aead/aes/vp.rs
- src/aead/aes_gcm.rs
Rust doesn't give us much control over inlining or prioritizing branches without PGO. Try to steer it in a good direction with the limited tools we have.
> aes_gcm: Rearrange CPU feature detection in Key::new

- src/aead/aes_gcm.rs
- src/aead/chacha.rs
- src/cpu.rs
- src/cpu/intel.rs
- src/digest/sha2/sha2_32.rs
When retrieving multiple flags at once, cache the flags in a `Values` structure and then test the flags set in that cached value. This has no effect with the current `spin::Once`-based implementation, but it helps the `race::OnceNonZeroUsize` implementation avoid some redundant loads.
> cpu: Add basic caching for cpu feature flags.

- Cargo.toml
- src/cpu.rs
- src/cpu/intel.rs
- src/polyfill.rs
- src/polyfill/once_cell/LICENSE-APACHE
- src/polyfill/once_cell/LICENSE-MIT
- src/polyfill/once_cell/README.txt
- src/polyfill/once_cell/race.rs
Here's a representative example of how this changes the generated assembly in callers:
```
@@ -36,14 +36,11 @@
lea r12, [rcx - 4]
3343
Acquire => intrinsics::atomic_load_acquire(dst),
-	mov rax, qword ptr [rip + ring::cpu::intel::featureflags::FEATURES@GOTPCREL]
-	movzx eax, byte ptr [rax + 4]
-		match self.status.load(Ordering::Acquire) {
-	cmp al, 2
-		if let Some(value) = self.get() {
-	jne .LBB85_2
+	mov rax, qword ptr [rip + ring::cpu::intel::featureflags::FEATURES]
+		match NonZeroUsize::new(val) {
+	test rax, rax
+	je .LBB85_2
movabs rax, 274877906881
if input.len() > MAX_IN_OUT_LEN {
@@ -104,10 +101,9 @@
if in_out.len() >= SSE_MIN_LEN {
cmp r12, 129
jb .LBB85_8
-		*features
-	mov rax, qword ptr [rip + ring::cpu::intel::featureflags::FEATURES@GOTPCREL]
-	mov eax, dword ptr [rax] …
```
> Remove spin dependency on x86 and x86_64 targets.

- Cargo.toml
- crypto/internal.h
- src/cpu.rs
- src/cpu/arm.rs
- src/polyfill.rs
Modify `cpu::arm` to use the same initialization logic as `cpu::intel`.
> Drop `spin` dependency in favor of internal `OnceNonZeroUsize`.

- src/cpu/intel.rs
Prepare to refactor how CPU feature detection is done. No-op change.
> cpu::intel: Clarify CPU feature detection.

- src/aead/gcm/clmul.rs
PSHUFB is used, which is SSSE3.
> AES-GCM: Require SSSE3 for CLMUL-based implementation.

- src/aead/chacha.rs
- src/cpu/intel.rs
The checking for the FXSR bit is an anachronism from OpenSSL, where it was used as a way to indicate that SSE instructions should not be used. Currently we require SSE/SSE2 to be available. In the future, if we make SSE/SSE2 optional, then we'll need to condition the SSSE3 feature on SSE (operating system) support.
Remove the `Fxsr` CPU feature as we no longer check for it.
> aead::chacha internals: Stop checking FXSR bit.

- src/aead/chacha.rs
> chacha/x86: Remove unnecessary parentheses.

- src/cpu/intel.rs
> intel/x86: Don't set `extended_features_ebx`.

- src/cpu/intel.rs
> intel/x86: Don't detect SSE4.1.

- src/cpu/intel.rs
Make the control flow easier to understand.
> cpu::intel: Combine adjacent `#[cfg(target_arch = "x86_64")]`.

- src/aead/aes/ffi.rs
- src/aead/aes_gcm.rs
- src/aead/chacha/ffi.rs
- src/aead/chacha20_poly1305/integrated.rs
- src/aead/overlapping/base.rs
Make it clearer that the references are still non-dangling for the time the pointers are allowed to be used. This should be a NFC but better safe than sorry. It is also consistent with what we do elsewhere, e.g. in `arithmetic::inout`.
> aead internals: `into_input_output_len` -> `with_input_output_len`.

- src/cpu/arm.rs
Address a compiler warning about unused `use`.
> cpu::arm: Don't reference `AtomicU32` in Aarch64.

- src/arithmetic/montgomery.rs
Make it easier for Linux distro maintainers to minimize their patches.
> arithmetic: Clarify "x86" SSE2 requirement.

- src/aead/aes/hw.rs
Simplify feature detection logic. We don't have an easy way to test AES-NI without SSSE3, and it's not worth trying to hack something up.
> aes/x86/x86_64: Only use AES-NI when SSSE3 is available.

- build.rs
- crypto/internal.h
Enforce that SSE2 is enabled when compiling C code and configure the C compiler to use SSE2.
See each individual commit for details.
> Require SSE2 when compiling C code

- src/arithmetic/montgomery.rs
- src/prefixed.rs
Make it clear what the calling convention is.
> non-aarch64/arm/x86/x86_64: declare bn_mul_mont as `extern "C"`.

- src/arithmetic/bigint/private_exponent.rs
- src/limb.rs
Instead of scanning the private exponent limbs backwards during exponentiation, reverse the limbs during key loading and then scan forward.
> arithmetic: Reverse private exponent words during key loading.

- .github/workflows/ci.yml
This reverts commit 9a6d9e67c265adc5b29c11e8df8199bfc171a050. So we expect that CI will use cc-rs 1.2.13 or later now.
> Revert "CI: Force the use of cc-rs 1.2.10 on Apple targets temporarily."

- crypto/fipsmodule/modes/asm/ghash-x86.pl
- crypto/fipsmodule/modes/asm/ghash-x86_64.pl
- src/aead/aes_gcm.rs
- src/aead/gcm.rs
- src/aead/gcm/clmul.rs
- src/aead/gcm/clmulavxmovbe.rs
- src/aead/gcm/fallback.rs
- src/aead/gcm/ffi.rs
- src/aead/gcm/neon.rs
- src/polyfill/slice/as_chunks.rs
Notably, for clmulavxmovbe, use the AVX implementation instead of the SSSE3 implementation.
> x86/x86_64: Use multi-block ghash for single block updates.

- src/cpu/intel.rs
Trial static feature detection on x86-64. Our plan is to ramp up to x86-64-v3 and then all the features we use.
> x86_64: Statically detect X86_64-v2 features we use.

- src/digest/sha2/ffi.rs
`&mut [T; N]` has the same representation as `*mut [T; N]` but normally we don't use `&mut [T; N]` this way.
> sha2: Use `*mut` instead of `&mut` in FFI declarations.

- src/cpu/intel.rs
- src/digest/sha2/sha2_64.rs
At least on AMD 7950x (Zen 4) the AVX implementation seems to benchmark significantly worse.
> digest: Don't enable AVX implementation on AMD.

- Cargo.toml
- build.rs
Modified the conditional logic in build.rs to allow for the usage of the `-msse2` flag when using clang-cl as a cross-compiler simulating MSVC. This update ensures compatibility for environments where clang-cl is used for MSVC-style compilation, enabling the appropriate SSE2 optimizations in these cases.
- Adjusted logic to check for `clang-cl` in addition to MSVC.
- Ensured that `-msse2` flag is applied when compiling for x86 with clang-cl.
**_I agree to license my contributions to each file under the terms given
at the top of each file I changed._**
> Fix cross-compilation compatibility for MSVC simulation with clang-cl

- src/cpu/arm/fuchsia.rs
> Fuchsia AArch64: Detect SHA-512 CPU feature & clean up existing detection.

- src/arithmetic/x86_64_mont.rs
These don't need non-default visibility.
> arithmetic/x86_64: Fix visibility of assembly fn declarations.

- src/aead/aes_gcm.rs
- src/aead/aes_gcm/aarch64.rs
The AVX2 and AVX512/AVX10 VAES-VCLMUL implementations (not used yet) have very similar forms to the AArch64 implementation. Split the current AArch64 implementation into AArch64-spceific and general parts, so we can reuse the general parts.
```
git difftool HEAD^1:src/aead/aes_gcm.rs src/aead/aes_gcm/aarch64.rs
```
> ase-gcm: Generalize logic for integrated AArch64.

- src/aead/aes/ffi.rs
- src/arithmetic/limbs/x86_64/mont.rs
- src/bb/mod.rs
- src/bssl.rs
- src/c.rs
- src/ec/curve25519/ops.rs
- src/ec/curve25519/x25519.rs
Cargo.toml: Narrow and document `libc` dependency conditions.
> Use `core::ffi::{c_int, c_uint}` now that we have MSRV >= 1.64.

- src/aead/aes.rs
For *ring* 0.17.12, both of these tests pass for default release mode,
release mode with overflow-checks=true, and debug mode, on 64-bit and
32-bit targets.
For prior releases, `test_aes_gcm_counter_blocks_max_minus_one` passes
in all three modes.
For prior releases, `test_aes_gcm_counter_blocks_max` passes in default
release mode:
```
$ cargo test --lib test_aes_gcm_counter_blocks --release
[snip]
test aead::aes::aes_gcm_tests::test_aes_gcm_counter_blocks_max ... ok
test aead::aes::aes_gcm_tests::test_aes_gcm_counter_blocks_max_minus_one ... ok
```
But, for 64-bit targets, when overflow checks are enabled (including debug mode),
`test_aes_gcm_counter_blocks_max` fails:
```
$ RUSTFLAGS="-C overflow-checks=true" cargo test --lib test_aes_gcm_counter_blocks
[snip]
thread …
```
> aes_gcm: Add counter test for max input/output length.

- crypto/fipsmodule/aes/asm/aes-gcm-avx10-x86_64.pl
- crypto/fipsmodule/aes/asm/aes-gcm-avx2-x86_64.pl
[Adapted by Brian Smith to *ring*'s prior modifications.]
gcm_ghash_vpclmulqdq_avx2() executes vzeroupper only when len >= 32, as it was supposed to use only xmm registers for len == 16.  But actually it was writing to two ymm registers unconditionally for $BSWAP_MASK and $GFPOLY.  Therefore, there could be a slow-down in later code using legacy SSE instructions, in the (probably rare) case where gcm_ghash_vpclmulqdq_avx2() was called with len=16 *and* wasn't followed by a function that does vzeroupper, e.g. aes_gcm_enc_update_vaes_avx2().
(The Windows xmm register restore epilogue of
gcm_ghash_vpclmulqdq_avx2() itself does use legacy SSE instructions, so probably was slowed down by this, but that's just 8 instructions.)
Fix this by updating gcm_ghash_vpclmulqdq_avx2() to correctly use …
> Avoid using YMM registers in `gcm_ghash_vpclmulqdq_avx2_1`.

- src/arithmetic/ffi.rs
Either `8192` or `8 * 1024` would be right, but not half of each way. NFC since this is just a static assertion.
Also clarify the size of the alloca we're guarding.
> Fix typo in `BN_MONTGOMERY_MAX_WORDS`.

- src/aead/aes_gcm/aeshwclmulmovbe.rs
Thanks to GitHub user `@cr-tk` for noticing.
> aes-gcm/x86-64: Fix typo "remaining" -> "remaining" (NFC).

- build.rs
- crypto/fipsmodule/aes/asm/aes-gcm-avx2-x86_64.pl
- src/aead/gcm/vclmulavx2.rs
Instead of starting with the body of the original
`gcm_ghash_vpclmulqdq_avx2` and removing the multi-block support, start with
`gcm_gmult_vpclmulqdq_avx2` and add the XOR of `aad`.
The instruction scheduling seems a bit better. Also, this computes
`bswap(Xi ^ aad)` instead of `bswap(Xi) ^ bswap(aad)`, saving one pshufb.
Rename the function to `gcm_ghash_vpclmulqdq_avx2_16` to better reflect its
constraint on `aad_len_16`.
This is the diff between this function and BoringSSL's
`gcm_gmult_vpclmulqdq_avx2`, as of
14d05a3b27f6706f9842583af405163b434c5c0e.
```diff
--- a/crypto/fipsmodule/aes/asm/aes-gcm-avx2-x86_64.pl
+++ b/crypto/fipsmodule/aes/asm/aes-gcm-avx2-x86_64.pl
@@ -436,10 +436,17 @@ sub _ghash_4x {
return $code;
}
-# void gcm_gmult_vpclmulqdq_avx2(uint8_t Xi[16], const u128 …
```
> aes_gcm/x86_64: Tweak `gcm_ghash_vpclmulqdq_avx2_16`.

- Cargo.toml
`cargo asm` seems to work better without LTO.
> Use `lto = false` in release profile.

- build.rs
Replace:
pub const ([A-Z_]+): .+\n\s+name: \"\1\",\n\s+ty: EnvVarTy::([A-Z]+),\n\s+};
with:
define_env! { $1: $2 }
> build.rs: Ensure EnvVar names match (DRY).

- src/cpu/arm.rs
- src/cpu/intel.rs
- src/polyfill/once_cell/race.rs
This changes the codegen for places where we call `cpu::features()` as expected.
Examples:
```
adrp	x8, :got:_ZN4ring3cpu3arm12featureflags8FEATURES17habb4a2487137fb15E
mov	x19, x0
ldr	x8, [x8, :got_lo12:_ZN4ring3cpu3arm12featureflags8FEATURES17habb4a2487137fb15E]
-	ldar	x8, [x8]
+	ldr	x8, [x8]
cbz	x8, .LBB86_2
```
```
adrp	x8, :got:_ZN4ring3cpu3arm12featureflags8FEATURES17habb4a2487137fb15E
mov	x19, x4
mov	x20, x3
ldr	x8, [x8, :got_lo12:_ZN4ring3cpu3arm12featureflags8FEATURES17habb4a2487137fb15E]
mov	x21, x2
mov	x22, x0
sub	x23, x3, #4
-	ldar	x8, [x8]
+	ldr	x8, [x8]
cbz	x8, .LBB84_8
```
> cpu: Use relaxed ordering on AArch64.

- RELEASES.md
- src/cpu/arm/linux.rs
- src/cpu/arm/mod.rs
There are no aarch64-*-linux-uclibc targets. Use this knowledge to simplify the feature detection for Linux/Android.
Move the comment about uclibc to a better spot.
This is a step towards splitting AArch64/ARM feature detection.
> aarch64: Stop supporting uclibc; arm: refactor support.

- Cargo.toml
I hope that this allows code coverage measurement to find cases where there is a potential overflow panic, as the branch should show up as uncovered.
> CI: Add `overflow-checks = true` to release and bench profiles.

- src/aead/aes/hw.rs
- src/aead/aes/vp.rs
- src/aead/aes_gcm.rs
- src/aead/gcm/clmul.rs
- src/aead/gcm/neon.rs
Replace the punning with separate implementations so that code coverage can measure them better. The punning is avoided at construction of the key objects, but not necessarily everywhere else; this is good enough for us to see that each implementation is selected during coverage testing, while still minimizing duplication.
> AEAD: Reduce punning of architecture-specific implementations.

- src/aead/gcm/clmul.rs
- src/aead/gcm/clmulavxmovbe.rs
- src/aead/gcm/ffi.rs
- src/aead/gcm/neon.rs
- src/aead/gcm/vclmulavx2.rs
See each individual commit for details.
> aes-gcm: Remove the `htable_new!` macro

- src/aead/gcm/clmul.rs
- src/aead/gcm/clmulavxmovbe.rs
- src/aead/gcm/ffi.rs
- src/aead/gcm/neon.rs
- src/aead/gcm/vclmulavx2.rs
The macro wasn't doing much. This minimizes the scope of `unsafe` and paves the way for some future improvements.
> aes_gcm: Remove `ghash!` macro.

- .github/workflows/ci.yml
Don't measure coverage for doctests, bins, benchmarks, etc.
This works around a failure to build doctests in the coverage jobs which is probably caused by a compatibility-breaking change in Rust's new doctest-xcompile feature and/or its doctest bundling feature.
> CI: Only measure coverage for tests.

- .github/workflows/ci.yml
The doctests are built/run in separate test-doc jobs so we don't need to run them in test-features.
This will speed up CI slightly.
This will also work around some incompatibility introduced in recent Rust 1.87 and/or Nightly releases where linking the doctests fails when cross-compiling. (Rust recently started building doctests when cross-compiling where previously it ignored them during cross- compilation.)
> CI: Don't build/run doctests in test-features jobs.

- Cargo.toml
- src/cpu/arm/linux.rs
See https://github.com/rust-lang/stdarch/pull/1746. libc 0.2.172 added getauxval for 32-bit ARM Android.
> arm: Call `getauxval` through libc.

- src/aead/aes/fallback.rs
Help the optimizer optimize a bit. When this was in C, Clang wasn't Inlining them either (on x86 and arm, at least).
> aes fallback: Don't inline `sub_bytes` or `shift_rows`.

- src/aead/aes/fallback.rs
It isn't accessed through FFI any longer.
> aes fallback: Remove unnecessary `#[repr(C)]` from `Batch`.

- BUILDING.md
But the Windows ARM64 header in the right place.
Add some notes that would have been helpful when I was trying to figure out myself how to build *ring* from Git on Windows ARM64.
> BUILDING.md: Clarify some Windows-specific help.

- src/arithmetic/bigint.rs
- src/arithmetic/inout.rs
- src/limb.rs
Is `(r, a)` supposed to be interpreted as `(r, r, a)` or `(r, a, a)`? When I created this, I assumed it was obvious that it should be `(r, r, a)`. But, soon we'll need to be able to support the other interpretation. Instead, have the caller write `(InOut(r), a)` to make it obvious that `(r, r, a)`. is intended.
> arithmetic: Disambiguate meaning of two-argument `AliasingSlices3`.

- src/arithmetic/bigint.rs
- src/arithmetic/inout.rs
- src/arithmetic/limbs/aarch64/mont.rs
- src/arithmetic/limbs/x86_64/mont.rs
- src/arithmetic/montgomery.rs
Fix a performance regression from when we replaced `bn_mul_mont`.
`bn_mul_mont` used to check whether its two source operand pointers were equal, calling the squaring function if so. Our expectation when it was replaced was that every caller would statically know whether it was doing squaring or non-squaring, so this check was not needed. Unfortunately, we overlooked this one case.
> arithmetic/aarch64: Use optimized squaring in `elem_exp_consttime`.

- crypto/chacha/asm/chacha-x86.pl
- src/aead/chacha.rs
This reverts commit 6d0cbf5.  The performance benefit matters mostly in how it affects CI perf. If/when we redo the testing of `open_within` to make it more efficient, we can probably re-revert this.
> Revert "chacha/x86: Remove nohw ChaCha20 fallback."

- src/polyfill/slice/as_chunks_mut.rs
> polyfill: Combine `AsChunksMut::as_ptr()` definitions.

- Cargo.toml
This reverts commit 03b223dd56d11ab94bb05e533be8b1077a4a8f1c, so that we depend on windows-sys 0.60 again.
> Revert "Revert "Update windows-sys dependency to 0.60.""

- src/digest.rs
- src/digest/dynstate.rs
- src/hmac.rs
Shrink `digest::Context` by 8 bytes and `hmac::Context` by twice that.
> digest/hmac: Make `Context` types a bit smaller.

- src/aead/aes_gcm.rs
- src/aead/algorithm.rs
- src/aead/chacha20_poly1305/mod.rs
Increase uniformity of the internal API after commit fe8d6485d33be9e0a43daaf398d5b7c3c2095841.
> aead internals: Slightly refactor internal `seal` APIs.

- src/aead/aes_gcm/aeshwclmulmovbe.rs
- src/aead/gcm.rs
- src/aead/gcm/clmulavxmovbe.rs
The comments that `Xi` and `HTable` "should" be aligned is confusing. It might have mattered for performance on some old CPUs but it's no longer important, so remove them.
The comments also erroneously claimed that only 9 entries were needed, due to me misreading the assembly code when I wrote these comments. In fact, 12 entries are required.
> aes_gcm/x86_64: More precisely model CLMUL-AVX-MOVBE key type.

- src/aead/aes_gcm.rs
- src/aead/gcm.rs
- src/aead/gcm/clmul_x86.rs
- src/aead/gcm/clmul_x86_64.rs
- src/aead/gcm/ffi.rs
```
git diff HEAD^1:src/aead/gcm/clmul_x86_x86_64.rs src/aead/gcm/clmul_x86.rs
git diff HEAD^1:src/aead/gcm/clmul_x86_x86_64.rs src/aead/gcm/clmul_x86_64.rs
```
> aes_gcm/x86/x86_64: internals: More precisely model CLMUL key type.

- src/aead/aes/ffi.rs
With `assert_eq!()`, the compiler will not use NRVO, so the key will first be constructed on the stack and then copied. This assertion isn't really helpful as we've already ensured that the failure case of all these C initialization functions will never be triggered by the structure of `KeyValue`, so switching to `debug_assert_eq!` is safe.
> aes internals: Use `debug_assert_eq!()` for always-true condition.

- src/cpu/x86.rs
- src/cpu/x86_64.rs
Because the name `r` is used for multiple results, `r.eax` in the check for leaf 7 was using the results of the leaf 1 query instead of the results of the leaf 0 query. Fix this.
> cpu/x86/x86_64: Fix detection of extended features.

- build.rs
- crypto/fipsmodule/aes/asm/aesv8-armx.pl
- crypto/fipsmodule/aes/asm/aesv8-gcm-armv8.pl
- src/aead/aes.rs
- src/aead/aes/ffi.rs
- src/aead/aes/hw.rs
- src/aead/aes_gcm/aarch64.rs
Move the length-based control flow to Rust, removing the `assert!`, showing that the initialization really is infallible.
> aes/aarch64 internals: Clarify control flow for HW key construction.

- src/cpu.rs
- src/cpu/aarch64/mod.rs
- src/cpu/arm/mod.rs
- src/cpu/x86.rs
- src/cpu/x86_64.rs
Clarify the non-zeroedness of the value.
> cpu: Use `NonZero<T>`'s `BitOr<T>` implementation.

- src/aead/aes/vp.rs
- src/polyfill.rs
- src/polyfill/ptr.rs
- src/polyfill/slice.rs
- src/polyfill/start_ptr.rs
Use a new pattern that avoids any possibile method name collisions. Rename the functions to remove the underscore. Move them out of the polyfill prelude.
> polyfill: Refactor StartPtr/StartMutPtr.

- build.rs
- crypto/fipsmodule/aes/asm/aesv8-armx.pl
- src/aead/aes.rs
- src/aead/aes/hw.rs
We overlooked that ctr32_encrypt_blocks is optimized for even numbers of blocks; it does redundant work for a single block. Since we only use it for single-block encryption, this was a waste. Fix this by basing the single-block encryption on the old aes_hw_encrypt_block, modified to do the XOR. The new version takes separate `rd_key` and `rounds` parameters since we don't use `AES_KEY` on this target.
> aes/aarch64: simplify single-block encryption

- .github/workflows/ci.yml
Doctests are run in their own test-doc job. This avoids failures to link the doctests for aarch64-unknown-linux-musl, presumably because `$rustflags_self_contained` isn't being passsed in RUSTFLAGS to rustc.
> CI: Skip doctests in `test` jobs.

- crypto/fipsmodule/aes/asm/aesv8-armx.pl
Decryption doesn't make sense for the new variant of the function, and we have never(-ish) defined the decryption function anyway, so specialize the code for encryption only.
> aes/aarch64: Simplify es_hw_encrypt_xor_block.

- crypto/fipsmodule/sha/asm/sha512-x86_64.pl
Every entry in the tables was duplicated when the AVX2 implementation was added, but we don't use the AVX2 implementation, so undo the duplication. See OpenSSL commit c4558efbf3a44a1b5e68dce46347dd3888db4760.
> sha2/x86_64: Shrink tables.

- build.rs
- src/rand.rs
This PR adds support for the QNX target, As mentioned in #2429 since there is no CI support the test was run on both x86-64 and aarch64 qemu and the reports are attached.
[test_output-aarch64.txt](https://github.com/user-attachments/files/21707438/test_output-aarch64.txt)
[test_output-x86-64.txt](https://github.com/user-attachments/files/21707439/test_output-x86-64.txt)
> Add qnx support

- mk/install-build-tools.sh
It didn't seem to be required but recent failures in GitHub Actions seem to indicate it sometimes is.
> Ci: Add an `apt-get update` before installing packages.

- src/arithmetic.rs
- src/arithmetic/bigint.rs
- src/arithmetic/ffi.rs
- src/arithmetic/limbs/aarch64/mont.rs
- src/arithmetic/limbs/x86_64/mont.rs
- src/arithmetic/limbs512/storage.rs
Also, when we already return a `LimbSliceError`, prefer returning a (converted) `LenMismatchError` to `unreachable!()` even for unreachable cases.
> arithmetic: Add implicit conversion of `LenMismatchError` to `LimbSliceError`.

- src/arithmetic/bigint.rs
- src/arithmetic/bigint/boxed_limbs.rs
- src/arithmetic/bigint/modulus.rs
- src/arithmetic/bigint/modulusvalue.rs
- src/arithmetic/bigint/private_exponent.rs
- src/ec/suite_b/ops.rs
- src/limb.rs
- src/rsa/keypair.rs
- src/rsa/public_key.rs
- src/rsa/public_modulus.rs
Replace uses of the `Storage` type (externally) with a new `Uninit` type that defers allocation until we know what we want to write, then use `Vec's `FromIterator` to avoid unnecessarily writing zeros, where it is easy to do so. 
Replace uses of `Storage` internally with `BoxedLimbs`; `Storage` was really a `BoxedLimbs` with its contents hidden from external users, but it turns out that `Uninit` is all we really need.
> bigint: Reduce unnecessary zero-initialization during heap allocation.

- src/arithmetic/bigint.rs
- src/arithmetic/bigint/boxed_limbs.rs
- src/arithmetic/bigint/modulus.rs
- src/limb.rs
- src/polyfill.rs
- src/polyfill/slice.rs
- src/polyfill/uninit_slice.rs
- src/rsa/keypair.rs
- src/rsa/public_modulus.rs
Don't use `MaybeUninit` yet, but polyfill an API that would allow us to switch.
> arithmetic: Adapt `One` to support uninitialized output buffers.

- src/arithmetic/bigint.rs
- src/arithmetic/limbs/x86_64/mont.rs
- src/arithmetic/limbs512/scatter.rs
- src/arithmetic/limbs512/storage.rs
We don't actually need to pass arguments as `&[[Limb; 8]]` instead of `&[Limb]` in most cases. As long as one argument has a type like that, then we've ensured that the length is a multiple of 512 bits. In most cases we were calling `as_chunks[_mut]` on something and then immediately calling `as_flattened[_mut]` on it.
> bigint/x86_64: Eliminate most unnecessary chunking.
