.travis.yml, BUILDING.md, mk/ring.mk, mk/top_of_makefile.mk, mk/update-travis-yml.py
=> Get ring building on Mac OS X

src/digest/digest.rs
I agree to license my contributions to each file under the terms
given at the top of each file I changed.
=> Fix incorrect compilation flag in doc example.

src/test.rs
=> Don't unnecessarily create owned `PathBuf`.

.gitignore
Tiny, but this would be nice to have for the various other PRs I'm working on. (IntelliJ's Rust plugin is pretty good.)
=> Ignore files from JetBrains tools

src/digest/digest.rs
=> Correct documentation for OUTPUT_LEN constants.

src/ec/eddsa.rs
Followup on #479, for #459.
Before, we stored the bytes of the private and public key together in one contiguous array to support using the foreign `GFp_ed25519_sign` function. Now EdDSA signing is implemented in Rust, and we no longer use that function, so we can switch to a more direct internal representation.
=> Split internal storage of `Ed25519KeyPair`

src/ec/eddsa.rs
NOTE: currently based on the work in #506.
=> WIP: Cache private scalar and prefix

src/ec/curve25519/ops.rs, src/ec/curve25519/x25519.rs
=> X25519 and Ed25519 comment, constant cleanup

Cargo.toml, build.rs, pregenerate_asm/Cargo.toml
=> Update to rayon 1.0

src/aead/mod.rs, src/agreement.rs, src/debug.rs, src/digest/mod.rs, src/ec/mod.rs, src/ec/suite_b/ecdsa/signing.rs, src/ec/suite_b/ecdsa/verification.rs, src/hmac.rs, src/rsa/signing.rs
I don't have any particular preference for the output so I based it on #541.
=> impl core::fmt::Debug for hmac::SigningKey and hmac::SigningContext

.travis.yml, mk/travis-install-kcov.sh, mk/travis.sh, mk/update-travis-yml.py
I tried to make the commits not too broad in scope. I'm sorry I didn't see you were also working on re-enabling kcov. I should have filled an issue when I started to look into this.
=> Updates to Travis CI

src/hmac.rs, tests/hmac_tests.rs
=> Derive clone for hmac key

src/aead.rs, tests/aead_tests.rs
This `LessSafeKey` doesn't require the use of `NonceSequence`. It also allows opening and sealing with one key.
=> Add a less strict AEAD API

src/hkdf.rs
=> Add HKDF HMAC-SHA1 for lagacy use

.travis.yml, mk/travis.sh, mk/update-travis-yml.py
Only Nightly Rust supports `-Zprofile`.
=> Fix code coverage by expanding options and using Nightly Rust.

crypto/fipsmodule/sha/asm/sha512-x86_64.pl
Remove the AVX2 code at least until it complies with the Win64 ABI.
=> Update sha512-x86_64.pl to match BoringSSL in using AVX1.

crypto/fipsmodule/ec/gfp_p256.c, crypto/fipsmodule/ec/gfp_p384.c
=> Use `constant_time_select_w` consistently in P-256 and P-384 point selection.

BUILDING.md, README.md
=> Add cross-compiling documentation

Cargo.toml, src/rand.rs
As far as I can tell Illumos behaves exactly the same as Solaris here, so all is needed is to add it to the supported OSes.
=> Add illumos support

.travis.yml, README.md, mk/travis.sh, mk/update-travis-yml.py, src/cpu.rs
In addition, use Xcode 12 in CI/CD.
=> Fix aarch64-apple-ios build; add build-only/no-test jobs to CI/CD.

.coveralls.yml
Tell Coveralls to use travis-ci.com IDs.
=> CI/CD: Add .coveralls.yml.

mk/cargo.sh
Each commit in this MR has a commit message that describes the change it makes.
=> CI/CD: Correct minor errors and omissions in mk/cargo.sh.

mk/cargo.sh, mk/install-build-tools.sh
See each commit's commit message for details.
=> CI/CD: Better manage the version of Clang being used for the build

.github/workflows/ci.yml, BUILDING.md, build.rs, mk/install-build-tools.ps1
=> Build: Replace use of Yasm with use of Nasm for Windows assembly.

.github/workflows/ci.yml, src/ec/curve25519/ed25519/signing.rs, src/hmac.rs, src/lib.rs
=> Fix a bunch of tiny issues with the documentation & test `cargo rustdoc` in GitHub Actions.

Cargo.toml, src/rand.rs
This superseeds issue #966.
Tested-on: DragonFly 5.8.1
=> Fix compilation on DragonFly

src/limb.rs, src/test.rs
=> tests: Deal with Clippy complains for Rust 1.49.0

src/aead/chacha.rs
The code had this comment:
```
/// XXX: Although this takes an `Iv`, this actually uses it like a
/// `Counter`.
```
With the recent refactorings we can fix the type to be `&Counter`. Further
we can get rid of `CounterOrIv`.
=> Further improve ChaCha20 Counter/IV handling.

src/aead/chacha.rs
=> Chacha20 tests: Improve the tests

src/ec/curve25519/x25519.rs, src/rsa/padding.rs, tests/aead_tests.rs, tests/hmac_tests.rs
=> Make Clippy happy

Cargo.toml, src/aead/chacha.rs, src/aead/chacha/fallback.rs, src/polyfill.rs, src/polyfill/chunks_fixed.rs, tests/aead_tests.rs
See the comments in fallback.rs for more details on the origin.
=> Add a Rust ChaCha20 implementation.

tests/aead_tests.rs
=> AEAD tests: Refactor tests to improve coverage of the AEAD API

src/aead.rs, src/aead/aes.rs, src/aead/aes_gcm.rs, src/aead/chacha20_poly1305.rs, src/aead/less_safe_key.rs, src/aead/shift.rs
=> AEAD: Make the internal opening API more like `copy_within`

src/aead.rs, src/aead/aes_gcm.rs, src/aead/chacha20_poly1305.rs
Don't try to have a common code path between sealing and opening. That complication costs more than is saved by doing it separately.
=> AEAD: Simplify internal control flow.

build.rs
Simplify build.rs to make it easier to maintain. It seemed like the logic
being removed here wasn't always correct.
=> build.rs: Replace manual dirty file checking with cargo:rerun-if-changed.

mk/clippy.sh, src/aead/chacha/fallback.rs, src/limb.rs, src/pbkdf2.rs, src/rsa/padding.rs
Reduce the use of slice indexing and stop disabling some slicing-related Clippy lints.
=> Reduce the use of slice indexing

src/io/der.rs
Simplify the integer parsing code. Instead of jumping through hoops to use
the `untrusted` API for validating the syntax, take advantage of slice
patterns, which weren't available at the time the original code was written.
Eliminate redundancy in checking for non-zero values when parsing positive
integers.
=> io::der: Simplify ASN.1 integer parsing.

src/io/der.rs
The `let _ =` stuff makes it look like we're ignoring the result. It
isn't clear that `with_bad_i` was doing the check we needed. Merge
`with_good_i` and `with_bad_i` into one `with_i` and move the checks to
the calling code.
=> io::der: Clarify logic in integer tests.

.github/workflows/ci.yml
=> Use cargo-audit 0.15.0.

build.rs
Take a step towards supporting clang as the C compiler for -msvc
targets.
=> build.rs: Always use ".o" for object files.

build.rs, crypto/cpu-intel.c, crypto/curve25519/curve25519.c, crypto/fipsmodule/aes/aes_nohw.c, crypto/fipsmodule/ec/ecp_nistz384.inl, crypto/fipsmodule/ec/p256-x86_64.c, crypto/fipsmodule/ec/p256.c, crypto/internal.h, crypto/poly1305/poly1305.c
See each individual commit message for details. We don't have CI/CD coverage for this build configuration yet, but I tested it locally.
=> Add support for building for {i686,x86_64}-pc-windows-msvc using clang/clang-cl 12.

build.rs
Localize the use of the "is git" check to a single place and use more
descriptive variables for the various effects that this check has.
As a nice side effect, the loosly-typed `warnings_are_errors` parameters
that were threaded through functions are now gone.
=> build.rs: Refactor away `Target::is_git` to clarify logic.

build.rs
Make the limited role of the `env` part of the target triple more clear.
=> build.rs: Replace `Target::env` with `Target::is_musl`.

Cargo.toml, build.rs, src/rand.rs
=> Use /dev/urandom for SecureRandom on Redox

src/rsa/padding.rs
Previously, `mgf1()` wrote the mask to the buffer, and then we XOR'd
the data onto the mask. Now, `mgf1()` XOR's the mask onto the data
that is already in the `out` buffer.
=> Refactor RSA PSS MGF processing to enable future use by OAEP.

.cargo/audit.toml, .github/workflows/ci.yml
=> CI: Fix `audit` job.

src/ec/suite_b/private_key.rs, src/pkcs8.rs
The extra period breaks the URL.
=> Fix broken URL in PKCS#8 docs

Cargo.toml, src/aead/gcm.rs, src/digest.rs, src/endian.rs, src/rsa/public_exponent.rs
=> Revert "Document or remove some uses of `unsafe`"

.github/workflows/ci.yml
Add the powerpc-unknown-linux-gnu target to `test`. Remove PowerPC and s390x targets from `test-features` because they slow down CI too much.
=> CI: Remove PowerPC and s390x jobs from test-features. Add PowerPC to test.

crypto/curve25519/curve25519_64_adx.c, third_party/fiat/curve25519_64_adx.h
=> Improve compatibility with older versions of GCC/Clang

build.rs
=> build.rs: Override fewer C compiler flags

src/rand.rs
the impl in getrand: https://github.com/rust-random/getrandom/blob/master/src/hermit.rs
=> Add support for Hermit OS.

bench/aead.rs
When this benchmark was imported from crypto-bench to *ring* and ported from the libtest `#[bench]` framework to Criterion.rs, we kept the macro-based structure from the original benchmarks. However, Criterion.rs actually supports the kind of parameterized benchmarking we do much more naturally, and so we don't need the macros. Get rid of them.
Also remove distinction between TLS 1.2 and TLS 1.3 AAD. These benchmarks were originally written long ago when the TLS 1.3 draft specified a different AAD format.
I hope this will serve as a better example of how to write such benchmarks than it previously did.
=> AEAD benchmarks: Rewrite to avoid macros.

src/arithmetic/bigint/modulus.rs, src/arithmetic/montgomery.rs, src/arithmetic/n0.rs
See individual commits for details.
=> NFC bigint: Misc. cleanup.

src/arithmetic/bigint.rs
Clarify how the math works, and use a slightly better trade-off of doubling vs squaring. On 64-bit targets RSA verification is now less than 10% faster. On 32-bit targets its over 20% faster. I
expect that we can improve the performance further by optimizing the doubling implementation.
Also the new implementation avoids allocating/cloning any temporary `Elem`s, unlike the previous implementation.
=> bigint: Use a better Montgomery RR doubling-vs-squaring trade-off.

src/arithmetic/bigint.rs, src/arithmetic/bigint/modulus.rs, src/rsa/keypair.rs
=> RSA: Use dynamic checks for widening conversions

bench/aead.rs
It looks like this was missed by 6cda863
=> bench aead: Do Cartesian product, not zip

mk/generate_curves.py, src/ec/suite_b/ecdsa/signing.rs, src/ec/suite_b/ecdsa/verification.rs, src/ec/suite_b/ops.rs, src/ec/suite_b/ops/p256.rs, src/ec/suite_b/ops/p384.rs
=> ec suite_b: Better encapsulate scalar arithmetic operations

.github/workflows/ci.yml
=> CI: Clean up GitHub Actions jobs a bit

src/digest.rs
Take a step towards refactoring the CPU feature detection.
=> digest: Remove CPU features from the digest context.

tool/generate_tests.cc
The generation of these tests was replaced by crypto/fipsmodule/ec/make_ec_scalar_base_mult_tests.go in *ring*'s source tree).
The twin-mul test generation was left since there's no replacement in the *ring* source tree, though it seems we never have used its output. Before using them we should probably try to adapt the Go generator instead; if that succeeds, we should remove `GeneratePointMulTwinTests` too.
=> generate_tests.cc: Remove ecc-*-point-mul[-base] test generation.

bench/aead.rs
This makes the results directly comparable to BoringSSL and OpenSSL
=> bench: Report throughput in AEAD benchmarks

build.rs
Pregenerate symbol prefixing headers so users of `cargo vendor` who use alternative build systems like Bazel or GN do not have to write any build logic to generate them.
=> Include generated symbol prefix header files in published releases.

build.rs
cc-rs now appears to do the right thing, so remove the workaround. This removes the dependency on cc-rs from the preassembly step and simplifies the logic.
=> build.rs: Pass aarch64-pc-windows-msvc .S files directly to cc-rs.

build.rs
If we're not using pregenerated sources, then just immediately generate the sources and then continue on using the same logic as we use when we are using pregenerated sources. This makes things easier to understand and maintain.
=> build.rs: Unify the way generated sources are processed.

build.rs, mk/package.sh, mk/publish.sh, src/lib.rs
=> Make packaging/publishing scripts more robust

src/cpu/arm.rs
Clarify the AArch64 case considerably by using the libc declarations for the function and all constants. Also clarify that NEON is statically guaranteed by the compiler to be available on AArch64.
Clarify the 32-bit ARM case slightly.
=> Linux/Android: Use libc definitions of HWCAPs on AArch64.

src/cpu/arm.rs
Make `detect_feature` a safe function by haivng it do a (clearly superfluous) check on the well-formedness of its input.
=> aarch64-apple-*: Improve `unsafe` usage.

src/aead/aes.rs
Use the same type definition for counters as BoringSSL and `aes_nohw_ctr32_encrypt_blocks`. This should be a no-op for correctness as the representation is effectively the same, except now with looser (u8 vs u32) alignment. This is much clearer though, and removing the type punning paves the way for aes_nohw.c to be replaced with Rust code.
=> AES-GCM internals: Use consistent definitions for `Counter`.

src/aead/aes_gcm.rs
When we use `aes_gcm_enc_kernel` it will process all the whole blocks, leaving only the last partial block, if any. Clarify this in the sealing implementation. With this change, the compiler understands what's happening well enough to jump directly to processing the last partial block after calling `aes_gcm_enc_kernel`.
Ideally we'd do the same for the opening implementation, but we can't right now due to the support for overlapping input/output. We should revisit this later when we have a better abstraction for that.
=> AES-GCM AArch64: Clarify integrated AES-GCM control flow.

src/aead/chacha20_poly1305.rs
Put the types into a submodule so we can qualify references to them, to disambiguate them from `aead::inout::inOut`.
=> Chacha20-Poly1305 internals: put `InOut` types into a submodule.

src/aead/chacha.rs
Eliminate the "less safe" variant of `encrypt_within`. Move the check for overlapping buffers into the inner safe wrapper around the assembly function call, so that it is clear what we're giving the assembly function.
The extra checks are only done for 32-bit ARM and 32-bit x86, which are less of a performance priority now. And also the checks probably don't affect performance anyway.
=> ChaCha20-Poly1305 internals: Clarify memory safety of `encrypt_within`.

src/cpu/arm.rs, src/cpu/arm/darwin.rs, src/cpu/arm/fuchsia.rs, src/cpu/arm/linux.rs, src/cpu/arm/windows.rs
Clarify the conditions in which each implementation is used. Move each OS-specific implementation into its own source file.
To review:
```
git difftool HEAD^1:src/cpu/arm.rs src/cpu/arm/darwin.rs
git difftool HEAD^1:src/cpu/arm.rs src/cpu/arm/linux.rs
git difftool HEAD^1:src/cpu/arm.rs src/cpu/arm/fuchsia.rs
git difftool HEAD^1:src/cpu/arm.rs src/cpu/arm/windows.rs
```
=> cpu::arm: Use `cfg_if!` to clarify target conditionals.

src/cpu/arm/linux.rs
Work around a toolchain bug to avoid illegal instruction errors on many Raspberry Pi and other devices. See the added comments for details.
=> AArch64/ARM Linux: Force dynamic detection for all non-NEON features.

src/aead/aes.rs
It turns out BSAES isn't the only one that required a non-empty in/out; at least the x86-64 implementation of `aes_hw_ctr32_encrypt_blocks` requires a non-empty in/out as well. Just assume all of them require it.
As the code currently exists, this is a no-op because `ctr32_encrypt_within` is never called with an empty in/out, but this would prevent memory safety issues if/when that changes.
=> AES: Use `NonZero_size_t` for ctr32_encrypt functions.

crypto/fipsmodule/aes/aes_nohw.c
The C code is never built with `OPENSSL_SSE2` so this has been dead code. Don't put any effort into getting it to work as there seems to be very little interest performance where SSE2 is available but SSSE3 isn't.
=> x86/x86_64: Remove fallback SSE2 AES implementation.

build.rs
It doesn't make sense to use c.try_get_compiler() after calling c.get_compiler().
=> build.rs: Clarify compiler detection.

src/cpu.rs, src/cpu/arm.rs, src/cpu/intel.rs
Completely separate the storage of flags on a per-architecture basis, so that ARM/Aarch64 and x86/x86_64 code paths can begin to further diverge in how they handle CPU feature flags.
Reduce the scope of each of the `static mut` declarations to the minimum, and encapsulate the access to each in a minimal, safe internal API.
Within the implementations of those new internal APIs, use `addr_of!`/`addr_of_mut!` and `ptr::{read,write}` to access the `static mut` fields.
=> cpu: Reduce scope of `unsafe` and clarify safety properties.

mk/generate_curves.py, src/arithmetic/bigint.rs, src/constant_time.rs, src/constant_time/leaky.rs, src/constant_time/word.rs, src/ec/suite_b/ops.rs, src/ec/suite_b/ops/p256.rs, src/ec/suite_b/ops/p384.rs, src/limb.rs
Introduce a new type alias for words that are not intended to be secret, and clarify some aspects of `Word` and the new `LeakyWord`.
=> constant_time: Introduce LeakyWord.

src/arithmetic.rs, src/arithmetic/bigint.rs, src/arithmetic/bigint/modulus.rs, src/arithmetic/bigint/modulusvalue.rs, src/arithmetic/montgomery.rs, src/bits.rs, src/lib.rs, src/rsa.rs
It's better to review this commit-by-commit.
=> arithmetic internals: Rearrange limb length limit definitions

crypto/fipsmodule/sha/asm/sha256-armv4.pl
It is dead code as we don't support hardware crypto for 32-bit ARM.
=> digest: Remove unused 32-bit ARM hardware SHA-256 implementation.

src/constant_time.rs
The C code correctly handles zero-length inputs by avoiding use of the pointers, but technically there may be UB since a Rust dangling pointer isn't a valid C pointer. Avoid the whole thing by adding a redundant length check on the Rust side.
=> constant_time: Clarify memory safety.

src/arithmetic/montgomery.rs, src/arithmetic/x86_64_mont.rs
Replace the use of `ControlFlow` with stronger input types.
Besides `ControlFlow` being an unusual thing for this codebase, this also is a step towards making `bn_sqr8x_mont` easier to call from other callers in the future.
Rename `bn_sqr8x_mont` to `sqr_mont5` to match the naming of the other `...5` functions in the module.
=> arithmetic: Use AsChunks to clarify `sqr_mont5`.

src/aead/aes_gcm.rs, src/arithmetic/bigint.rs, src/arithmetic/x86_64_mont.rs, src/polyfill/slice/as_chunks.rs, src/polyfill/slice/as_chunks_mut.rs
Do the check that the limbs count is divisible by 8 in one place.
=> arithmetic: Use AsChunks/AsChunksMut in `elem_exp_consttime`.

.github/workflows/ci.yml, mk/package.sh
Packaging and publishing should use the MSRV to maximize compatibility.
=> mk/package.sh: Use MSRV for packaging.

src/cpu.rs, src/cpu/arm.rs, src/cpu/intel.rs
Make them more similar to each other, at least.
=> cpu: Further unify ARM & Intel.

src/cpu/intel.rs
*ring*'s policy is, in general, to precisely cite specifications/documentation with minimal quoting so that copy/paste errors are less likely to cause misunderstandings. Accordingly, remove a bunch of quotes from Intel/AMD documentation.
Further clarify the remaining comments.
=> cpu::intel: Reduce quoting and clarify comments.

crypto/fipsmodule/modes/asm/ghash-ssse3-x86.pl, crypto/fipsmodule/modes/asm/ghash-ssse3-x86_64.pl, src/aead/gcm/ffi.rs
Don't hook them up yet, though. See each commit for details.
=> Import SSSE3 GHASH implementations from BoringSSL

crypto/fipsmodule/ec/p256-nistz.c, crypto/fipsmodule/ec/p256_shared.h
Remove trivial and unneeded differences.
=> Sync crypto/fipsmodule/ec/p256* with upstream.

src/arithmetic.rs, src/arithmetic/bigint.rs, src/arithmetic/limbs/aarch64/mod.rs, src/arithmetic/limbs/aarch64/mont.rs, src/arithmetic/limbs/mod.rs, src/arithmetic/limbs/x86_64/mod.rs, src/arithmetic/limbs/x86_64/mont.rs, src/arithmetic/montgomery.rs
Prepare for the expansion of architecture-specific Rust code.
=> arithmetic/aarch64/x86_64: Refactor module structure.

src/aead/aes_gcm.rs, src/aead/aes_gcm/aeshwclmulmovbe.rs
```
git difftool HEAD^1:src/aead/aes_gcm.rs \
src/aead/aes_gcm/aeshwclmulmovbe.rs
```
=> aes_gcm: Split x86-64 integrated implementation into its own module.

tests/quic_tests.rs
=> quic tests: Clarify and expand

crypto/fipsmodule/aes/asm/aes-gcm-avx10-x86_64.pl
Move the Perl code that generates gcm_gmult_vpclmulqdq_avx10() to earlier in the file, so that it matches aes-gcm-avx2-x86_64.pl.  Also add comments that explain why gcm_gmult_vpclmulqdq_avx2() and gcm_gmult_vpclmulqdq_avx10() do not use vzeroupper.
No change to the generated assembly code except whitespace.
Change-Id: I74c7a7973f55bfd6a6c1663b9f20c0c7f178232c
Reviewed-on: https://boringssl-review.googlesource.com/c/boringssl/+/77767
Commit-Queue: David Benjamin <davidben@google.com>
Reviewed-by: David Benjamin <davidben@google.com>
=> Move gcm_gmult_vpclmulqdq_avx10 and add comment

crypto/cpu_intel.c, crypto/fipsmodule/aes/asm/aes-gcm-avx2-x86_64.pl, crypto/fipsmodule/aes/asm/aes-gcm-avx512-x86_64.pl
See each commit for details.
```
git diff 14d05a3b27f6706f9842583af405163b434c5c0e -- \
crypto/fipsmodule/aes/asm/aes-gcm-avx512.pl
```
=> aes-gcm/x86_64: Cherry-pick recent AVX-512 changes from BoringSSL

src/arithmetic/ffi.rs
This is a follow-up to 8596c783a5596543bda4acf18df376dce00b26bc.
=> arithmetic: Update comments & assertions regarding `MIN_LIMBS`.

build.rs
`CARGO_MANIFEST_DIR` should be allowed to change without triggering a rebuild. Related to #2454.
=> Don't rebuild when various Cargo-set environment variables like `CARGO_MANIFEST_DIR` change.

src/aead/aes_gcm.rs, src/aead/aes_gcm/aeshwclmulmovbe.rs, src/aead/algorithm.rs, src/aead/gcm.rs, src/aead/less_safe_key.rs, src/aead/overlapping/base.rs, src/polyfill/slice/as_chunks.rs
=> aead: Refactor internal API to clarify interface

Cargo.toml
This reverts commit b70dcfe933c35b6d451d683f13d3f27e72494815.
=> Revert "Update windows-sys dependency to 0.60."

src/bb/boolmask.rs, src/bb/bytes.rs, src/tests/bb_boolmask_tests.rs, src/tests/bb_bytes_tests.rs, src/tests/c_constant_time_tests.rs, src/tests/mod.rs
```
git difftool HEAD^1:src/bb/mod.rs src/bb/bytes.rs
git difftool HEAD^1:src/bb/mod.rs src/tests/bb_boolmask_tests.rs
git difftool HEAD^1:src/bb/mod.rs src/tests/bb_bytes_tests.rs
```
=> bb: Split out "bytes" submodule and tests submodule.

src/cpu.rs, src/cpu/x86.rs, src/cpu/x86_64.rs
```
git difftool HEAD^1:src/cpu/intel.rs src/cpu/x86.rs
git difftool HEAD^1:src/cpu/intel.rs src/cpu/x86_64.rs
```
=> cpu: Split x86 and x86_64 implementations.

.github/workflows/ci.yml
This reverts commit 7105c9dd6a34c032eaedab499e55411de168bfd1.
=> Revert "CI: use codecov/codecov-action@v5."

.github/workflows/ci.yml
This reverts commit 52f85ce1527347818c1284774b7469522354c7ca.
=> Revert "Revert "CI: use codecov/codecov-action@v5.""

.github/workflows/ci.yml, src/cpu/aarch64/mod.rs
Stop from building until we have tested it.
=> arm64_32-apple-watchos: Stop from building.
